import { Component, OnInit } from '@angular/core';

export interface SkillGemList {
  name: string;
  level: number;
  support: string;
  default: string;
  alt1: string;
  alt2?: string;
  alt3?: string;
}

const DATA: SkillGemList[] = [
  {
    level: 16,
    name: 'Ancestral Cry',
    support: 'Active',
    default: '10% increased Cooldown Recovery Rate',
    alt1: '40% increased Warcry Speed',
    alt2: 'Buff grants 20% increased Armour',
  },
  {
    level: 4,
    name: 'Ancestral Protector',
    support: 'Active',
    default: '20% increased Totem Damage',
    alt1: '40% increased Totem Placement speed',
    alt2: '40% increased Activation range',
    alt3: '20% increased Buff Effect',
  },
  {
    level: 28,
    name: 'Ancestral Warchief',
    support: 'Active',
    default: '20% increased Totem Damage',
    alt1: '40% increased Totem Placement speed',
    alt2: '40% increased Activation range',
    alt3: '40% increased Damage with Ailments',
  },
  {
    level: 24,
    name: 'Anger',
    support: 'Active',
    default: '40% increased Area of Effect',
    alt1: 'You and nearby Allies deal 20% increased Burning Damage',
    alt2: 'You and nearby allies gain 5% increased Movement Speed',
  },
  {
    level: 28,
    name: 'Animate Guardian',
    support: 'Active',
    default: 'Minions have 40% increased Movement Speed',
    alt1: 'Minions have 60% increased Area of Effect',
    alt2: '40% increased Minion Maximum Life',
  },
  {
    level: 4,
    name: 'Animate Weapon',
    support: 'Active',
    default: 'Minions have 20% increased Movement Speed',
    alt1: 'Minions have 10% chance to Intimidate Enemies for 4 seconds on Hit',
    alt2: '20% chance to create an additional Animate Weapon copy',
    alt3: 'Minions deal 0 to 100 Added Lightning Damage',
  },
  {
    level: 12,
    name: 'Arc',
    support: 'Active',
    default: '10% chance to Shock enemies',
    alt1: '20% increased Chaining range',
    alt2: '10% increased Damage for each time this Skill has Chained',
    alt3: '20% reduced Enemy Stun Threshold'
  },
  {
    level: 16,
    name: 'Arcane Cloak',
    support: 'Active',
    default: '20% increased Skill Effect Duration',
    alt1: '5% of Damage taken gained as Mana over 4 seconds when Hit',
    alt2: '10% increased Buff Effect',
  },
  {
    level: 38,
    name: 'Arcanist Brand',
    support: 'Active',
    default: '10% increased Activation frequency',
    alt1: 'Supported Skills have 10% increased Area of Effect',
    alt2: 'Supported Skills have 20% increased Projectile Speed',
    alt3: 'Supported Skills have 20% increased Chaining range'
  },
  {
    level: 16,
    name: 'Arctic Armour',
    support: 'Active',
    default: '20% increased Skill Effect Duration',
    alt1: '20% chance to Freeze Enemies for 350 ms when Hit',
    alt2: '1% less Physical Damage taken from Hits, 1% less Fire Damage taken from Hits',
  },
  {
    level: 28,
    name: 'Armageddon Brand',
    support: 'Active',
    default: '10% increased Cast Speed',
    alt1: '5% chance to deal Double Damage',
    alt2: '20% chance for Brands to Attach to a new Enemy each time they Activate',
  },
  {
    level: 28,
    name: 'Artillery Ballista',
    support: 'Active',
    default: '20% increased Fire Damage',
    alt1: '100% increased Burning Damage',
    alt2: 'Fires an additional Arrow',
  },
  {
    level: 24,
    name: 'Assassins Mark',
    support: 'Active',
    default: 'Cursed Enemies have a 5% chance to grant a Power Charge when Hit',
    alt1: 'Cursed enemies take 4% increased Damage',
    alt2: 'Hits against Cursed Enemies have +0.2% to Critical Strike Chance',
  },
  {
    level: 28,
    name: 'Ball Lightning',
    support: 'Active',
    default: '20% increased Lightning Damage',
    alt1: '10% increased Cast Speed',
    alt2: 'Projectiles have 10% chance to be Supercharged',
  },
  {
    level: 24,
    name: 'Bane',
    support: 'Active',
    default: 'Applied Curses have 10% increased Effect',
    alt1: '10% increased Effect of Supported Curses, 20% increased Skill Effect Duration',
    alt2: 'Enemies have 10% chance to Explode on Death, dealing a quarter of their maximum Life as Chaos Damage',
  },
  {
    level: 12,
    name: 'Barrage',
    support: 'Active',
    default: '10% increased Projectile Damage',
    alt1: '20% chance to Knock Enemies Back on hit',
    alt2: '10% increased Attack Speed',
    alt3: 'Inflict non-Damaging Ailments as though dealing 100% more Damage',
  },
  {
    level: 4,
    name: 'Bear Trap',
    support: 'Active',
    default: '20% increased Physical Damage',
    alt1: '40% increased Skill Effect Duration',
    alt2: '10% increased Cooldown Recovery Rate',
    alt3: '20% chance to Impale Enemies on Hit',
  },
  {
    level: 34,
    name: 'Berserk',
    support: 'Active',
    default: '20% increased Attack Damage',
    alt1: '10% increased Cooldown Recovery Rate',
    alt2: 'Buff grants 20% more Spell Damage',
  },
  {
    level: 16,
    name: 'Blade Blast',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '+10% to Chaos Damage over Time Multiplier',
    alt2: '10% chance to Impale on Spell Hit',
    alt3: '10% increased Cast Speed',
  },
  {
    level: 28,
    name: 'Blade Flurry',
    support: 'Active',
    default: '10% increased Attack Speed',
    alt1: 'Final Flurry has 20% increased Area of Effect',
    alt2: '40% increased Elemental Damage while Channelling',
  },
  {
    level: 12,
    name: 'Blade Vortex',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '0.4% of Damage Leeched as Life',
    alt2: '20% chance to create an additional Blade',
    alt3: '60% increased Damage while you have 5 or fewer Blades',
  },
  {
    level: 28,
    name: 'Bladefall',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '20% chance to Knock Enemies Back on hit',
    alt2: '40% increased distance between Volleys',
  },
  {
    level: 28,
    name: 'Bladestorm',
    support: 'Active',
    default: '20% increased Skill Effect Duration',
    alt1: 'Sand Bladestorms move with 20% increased speed',
    alt2: 'Blood Bladestorm deals 40% increased Damage with Ailments',
    alt3: '40% chance to create the wrong Bladestorm',
  },
  {
    level: 28,
    name: 'Blast Rain',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '5% chance to Cover Enemies in Ash on Hit',
    alt2: '40% increased Damage to distant Enemies',
    alt3: 'Arrows fall within a 60% increased Area of Effect',
  },
  {
    level: 12,
    name: 'Blazing Salvo',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '40% increased Projectile Speed',
    alt2: 'Gain 5% of Fire Damage as Extra Chaos Damage',
  },
  {
    level: 1,
    name: 'Blight',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '20% increased Chaos Damage',
    alt2: '60% increased Secondary Duration',
  },
  {
    level: 10,
    name: 'Blink Arrow',
    support: 'Active',
    default: '30% increased Arrow Speed',
    alt1: 'Minions have 20% increased Duration',
    alt2: '60% increased Minion Maximum Life',
    alt3: '+1 Cooldown Use',
  },
  {
    level: 16,
    name: 'Blood Rage',
    support: 'Active',
    default: '5% increased Attack Speed',
    alt1: 'Buff grants 2% chance to gain a Frenzy Charge when you Hit a Unique Enemy',
    alt2: 'Buff grants 0.4% of Elemental Attack Damage leeched as Life',
  },
  {
    level: 4,
    name: 'Blood and Sand',
    support: 'Active',
    default: '10% increased Cooldown Recovery Rate',
    alt1: '20% increased Projectile Attack Damage while in Blood Stance, 20% increased Projectile Speed while in Sand Stance',
    alt2: 'Spells deal 20% increased Area Damage while in Blood Stance, Spells have 10% increased Area of Effect while in Sand Stance',
  },
  {
    level: 10,
    name: 'Bodyswap',
    support: 'Active',
    default: '10% increased Cast Speed',
    alt1: '100% increased Burning Damage',
    alt2: '10% increased Area of Effect',
    alt3: '40% increased Damage if not Consuming a Corpse',
  },
  {
    level: 12,
    name: 'Bone Offering',
    support: 'Active',
    default: 'Grants Minions 10% increased Cast Speed',
    alt1: '40% less Skill Effect Duration, Minions recover 100 Life when they Block',
    alt2: 'Grants Minions +2% Chance to Block Attack Damage, Grants Minions +2% Chance to Block Spell Damage',
  },
  {
    level: 16,
    name: 'Brand Recall',
    support: 'Active',
    default: 'Brands gain 20% increased Attachment Range',
    alt1: '20% increased Cooldown Recovery Rate',
  },
  {
    level: 1,
    name: 'Burning Arrow',
    support: 'Active',
    default: '+10% to Fire Damage over Time Multiplier',
    alt1: '60% increased Critical Strike Chance',
    alt2: 'Projectiles Pierce 2 additional Targets',
  },
  {
    level: 1,
    name: 'Caustic Arrow',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '20% chance to inflict Withered on Hit',
    alt2: '20% of Physical Damage Converted to Chaos Damage',
  },
  {
    level: 12,
    name: 'Chain Hook',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '+4 to radius',
    alt2: '20% increased Range',
  },
  {
    level: 28,
    name: 'Charged Dash',
    support: 'Active',
    default: '10% increased Attack Speed',
    alt1: '10% more Movement Speed',
    alt2: '20% increased travel distance',
  },
  {
    level: 10,
    name: 'Clarity',
    support: 'Active',
    default: '40% increased Area of Effect',
    alt1: 'You and nearby Allies have 10% increased Mana Recovery from Flasks',
    alt2: 'You and nearby Allies have 20% increased Damage while on Full Mana',
  },
  {
    level: 1,
    name: 'Cleave',
    support: 'Active',
    default: '10% increased Attack Speed',
    alt1: '+20 Life gained for each Enemy hit by your Attacks',
    alt2: '40% increased Area of Effect while not Dual Wielding',
    alt3: '100% chance to Destroy Corpses on Kill'
  },
  {
    level: 1,
    name: 'Cobra Lash',
    support: 'Active',
    default: '30% increased Critical Strike Chance',
    alt1: '20% increased Chaining range',
    alt2: 'Projectiles deal 15% increased Damage for each remaining Chain',
  },
  {
    level: 16,
    name: 'Cold Snap',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '20% increased Effect of Chill',
    alt2: '40% increased Damage with Hits and Ailments',
  },
  {
    level: 24,
    name: 'Conductivity',
    support: 'Active',
    default: 'Shocks on Cursed enemies have 20% increased Duration',
    alt1: 'Curses inflicted by this Skill have +5 to maximum Doom',
    alt2: 'Hits against Cursed Enemies have +20% chance to Shock',
  },
  {
    level: 28,
    name: 'Consecrated Path',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '10% increased Attack Speed',
    alt2: '10% increased teleport range',
    alt3: '40% increased Consecrated Ground Area'
  },
  {
    level: 4,
    name: 'Contagion',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '60% increased Chaos Damage',
    alt2: '60% chance to Spread when affected Enemy is Hit',
  },
  {
    level: 4,
    name: 'Conversion Trap',
    support: 'Active',
    default: '20% increased Skill Effect Duration',
    alt1: 'Converted Enemies have 20% chance to Taunt on Hit',
    alt2: 'Converted Enemies deal 400% increased Damage',
  },
  {
    level: 24,
    name: 'Convocation',
    support: 'Active',
    default: '20% increased Skill Effect Duration',
    alt1: '20% increased Cooldown Recovery Rate, Buff grants 40% increased Movement Speed',
    alt2: 'Unnerve nearby Enemies for 4.0 seconds, 40% reduced Cooldown Recovery Rate',
  },
  {
    level: 28,
    name: 'Crackling Lance',
    support: 'Active',
    default: '10% chance to Shock enemies',
    alt1: '20% of Lightning Damage Converted to Chaos Damage',
    alt2: 'Lose Intensity 20% slower while moving',
    alt3: '10% increased Cast Speed',
  },
  {
    level: 12,
    name: 'Creeping Frost',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '20% increased Skill Effect Duration',
    alt2: 'Fires an additional Projectile',
    alt3: 'Chilling Area has 40% increased Movement Speed',
  },
  {
    level: 28,
    name: 'Cremation',
    support: 'Active',
    default: '20% increased Fire Damage',
    alt1: '100% increased Burning Damage',
    alt2: 'Fires Projectiles 5% faster',
    alt3: '40% chance to Explode a nearby Corpse when Firing Projectiles',
  },
  {
    level: 28,
    name: 'Cyclone',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '20% chance to Knock Enemies Back on hit',
    alt2: '5% more Movement Speed',
    alt3: '20% Chance to Avoid Interruption from Stuns While Using this Skill',
  },
  {
    level: 28,
    name: 'Dark Pact',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: 'Sacrifices 1% of Skeletons Life to deal that much Chaos Damage',
    alt2: 'Minions recover 2% of Life on Hit',
  },
  {
    level: 4,
    name: 'Dash',
    support: 'Active',
    default: '10% increased Cooldown Recovery Rate',
    alt1: '20% increased travel distance',
    alt2: 'Grants Phasing for 2.0 seconds',
  },
  {
    level: 4,
    name: 'Decoy Totem',
    support: 'Active',
    default: '20% increased totem life',
    alt1: '40% increased Totem Placement speed',
    alt2: 'Totems Regenerate 20% of Life per second',
    alt3: 'Totems Explode on Death, dealing 40% of their Life as Physical Damage',
  },
  {
    level: 16,
    name: 'Desecrate',
    support: 'Active',
    default: '20% increased Cast Speed',
    alt1: '200% increased Chaos Damage',
    alt2: '60% chance to spawn an additional Corpse',
    alt3: 'Each Corpse spawned has 2% chance to be a Forgotten Corpse',
  },
  {
    level: 24,
    name: 'Despair',
    support: 'Active',
    default: 'Cursed enemies take 10% increased Damage from Damage Over Time effects',
    alt1: '10% increased Effect of Curse',
    alt2: 'Spell Hits have 10% chance to Hinder Cursed Enemies with 30% reduced Movement Speed for 4 seconds',
  },
  {
    level: 24,
    name: 'Determination',
    support: 'Active',
    default: '40% increased Area of Effect',
    alt1: 'You and nearby Allies have 20% chance to Avoid being Stunned',
    alt2: 'You and nearby Allies gain 10% of Evasion Rating as Extra Armour',
  },
  {
    level: 4,
    name: 'Detonate Dead',
    support: 'Active',
    default: '10% increased Cast Speed',
    alt1: '60% of Fire Damage Converted to Chaos Damage',
    alt2: 'Explosion deals 80% increased Damage if the Corpse is Ignited',
  },
  {
    level: 8,
    name: 'Detonate Mines',
    support: 'Active',
    default: 'Mines have 20% increased Detonation Speed',
    alt1: 'Recover 0.2% of Life for each Mine Detonated',
  },
  {
    level: 4,
    name: 'Devouring Totem',
    support: 'Active',
    default: '20% increased totem life',
    alt1: '100% increased Totem Duration',
    alt2: '40% increased Totem Placement speed',
  },
  {
    level: 28,
    name: 'Discharge',
    support: 'Active',
    default: '20% increased Elemental Damage',
    alt1: '40% increased Cast Speed',
    alt2: '10% chance to deal Damage without removing Charges',
    alt3: '40% increased Damage if three different Charge types removed',
  },
  {
    level: 24,
    name: 'Discipline',
    support: 'Active',
    default: '40% increased Area of Effect',
    alt1: 'You and nearby Allies have 10% increased Damage while on Full Energy Shield',
    alt2: 'You and nearby Allies gain 40% increased Energy Shield Recharge rate, You and nearby Allies have 30% slower start of Energy Shield Recharge',
  },
  {
    level: 28,
    name: 'Divine Ire',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '10% increased beam width',
    alt2: '20% of Physical Damage Converted to Cold Damage',
  },
  {
    level: 28,
    name: 'Dominating Blow',
    support: 'Active',
    default: 'Minions deal 20% increased Damage',
    alt1: '30% increased Minion Duration',
    alt2: 'Summoned Sentinels have 20% increased Cooldown Recovery Rate',
    alt3: 'Maximum 2 Summoned Normal Sentinels of Dominance',
  },
  {
    level: 1,
    name: 'Double Strike',
    support: 'Active',
    default: '10% increased Attack Speed',
    alt1: '40% increased Elemental Damage',
    alt2: '20% chance to Maim on Hit',
  },
  {
    level: 24,
    name: 'Dread Banner',
    support: 'Active',
    default: '10% increased effect of Aura',
    alt1: '60% less Skill Effect Duration, Nearby Enemies deal 2% less Damage',
    alt2: 'You and nearby Allies have 5% chance to Impale Enemies on Hit with Attacks',
  },
  {
    level: 1,
    name: 'Dual Strike',
    support: 'Active',
    default: '+10% to Critical Strike Multiplier',
    alt1: '20% increased Critical Strike Chance, +5 to Melee Strike Range',
    alt2: '100% increased Damage with Hits and Ailments against Enemies that are on Full Life',
    alt3: 'Deals 10% more added damage',
  },
  {
    level: 28,
    name: 'Earthquake',
    support: 'Active',
    default: '20% increased Damage',
    alt1: '20% increased Skill Effect Duration, 60% increased Damage',
    alt2: 'Initial Slam has 40% increased Area of Effect',
    alt3: 'Increases and Reductions to Spell Damage also apply to Attack Damage from this Skill'
  },
  {
    level: 12,
    name: 'Earthshatter',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '10% chance to create an additional Fissure',
    alt2: '20% increased Fissure Length',
    alt3: 'Fissures deal 60% more Damage, Spikes deal 60% less Damage',
  },
  {
    level: 12,
    name: 'Elemental Hit',
    support: 'Active',
    default: '20% increased Elemental Damage',
    alt1: '10% increased Area of Effect',
    alt2: '20% increased Effect of non-Damaging Ailments on Enemies',
  },
  {
    level: 24,
    name: 'Elemental Weakness',
    support: 'Active',
    default: 'Cursed enemies have -5% to Elemental Resistances',
    alt1: '10% increased Effect of Curse',
    alt2: '10% increased Duration of Elemental Ailments on Cursed enemies',
  },
  {
    level: 10,
    name: 'Enduring Cry',
    support: 'Active',
    default: '20% increased Skill Effect Duration',
    alt1: '40% increased Warcry Speed',
    alt2: '40% reduced Cooldown Recovery Rate, 20% increased Buff Effect',
  },
  {
    level: 24,
    name: 'Enfeeble',
    support: 'Active',
    default: '10% increased Effect of Curse',
    alt1: 'Curse has 40% increased Doom gain rate',
    alt2: 'Curse Skills have 10% increased Cast Speed',
  },
  {
    level: 16,
    name: 'Ensnaring Arrow',
    support: 'Active',
    default: '10% increased Attack Speed',
    alt1: '20% increased Area of Effect',
    alt2: 'Ensnared Enemies take 10% increased Spell Damage',
  },
  {
    level: 12,
    name: 'Essence Drain',
    support: 'Active',
    default: '20% increased Chaos Damage',
    alt1: 'Regenerate 0.10% of Debuff Damage as Life',
    alt2: '100% increased Damage with Hits',
  },
  {
    level: 1,
    name: 'Ethereal Knives',
    support: 'Active',
    default: '20% increased Projectile Speed',
    alt1: 'Fires 2 additional Projectiles',
    alt2: '10% chance to Impale on Spell Hit',
  },
  {
    level: 28,
    name: 'Explosive Arrow',
    support: 'Active',
    default: '20% increased Skill Effect Duration',
    alt1: '20% chance to Ignite enemies, 60% increased Critical Strike Chance',
    alt2: '40% less Skill Effect Duration, Maximum 4 Explosive Arrows stuck in an Enemy',
  },
  {
    level: 1,
    name: 'Explosive Trap',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '60% increased Burning Damage',
    alt2: '40% of Physical Damage Converted to Cold Damage',
  },
  {
    level: 12,
    name: 'Fire Trap',
    support: 'Active',
    default: '20% increased Fire Damage',
    alt1: '20% increased Skill Effect Duration',
    alt2: '20% less Area of Effect, 60% chance to Ignite enemies',
  },
  {
    level: 1,
    name: 'Fireball',
    support: 'Active',
    default: '20% increased Projectile Speed',
    alt1: '60% increased Area of Effect, 40% reduced Projectile Speed',
    alt2: '40% less Damage with Ignite, 60% increased Effect of non-Damaging Ailments on Enemies',
    alt3: '5% chance to Debilitate Enemies for 1 second on Hit',
  },
  {
    level: 28,
    name: 'Firestorm',
    support: 'Active',
    default: '20% increased Damage',
    alt1: 'Base duration is -0.06 seconds, First Impact deals 60% more damage',
    alt2: '20% reduced Enemy Stun Threshold',
  },
  {
    level: 10,
    name: 'Flame Dash',
    support: 'Active',
    default: '10% increased Cooldown Recovery Rate',
    alt1: '20% increased travel distance',
    alt2: '40% chance to Ignite enemies, 40% more Burning Damage',
  },
  {
    level: 12,
    name: 'Flame Surge',
    support: 'Active',
    default: '10% increased Cast Speed',
    alt1: '10% chance to Scorch Enemies',
    alt2: '+5 to Area of Effect length',
  },
  {
    level: 4,
    name: 'Flame Wall',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '+10% to Fire Damage over Time Multiplier, 20% reduced Skill Effect Duration',
    alt2: '40% increased Cast Speed',
    alt3: 'Inflicts Fire Exposure for 4 seconds when Enemies enter the wall, applying -10% to their Fire Resistance',
  },
  {
    level: 28,
    name: 'Flameblast',
    support: 'Active',
    default: '20% increased Damage',
    alt1: '40% of Fire Damage Converted to Chaos Damage, 20% chance to Poison on Hit',
    alt2: '2 maximum Stages',
    alt3: '+10 to radius, 10% less Area of Effect per Stage',
  },
  {
    level: 28,
    name: 'Flamethrower Trap',
    support: 'Active',
    default: '20% increased Fire Damage',
    alt1: '20% less Skill Effect Duration, 60% increased Cooldown Recovery Rate',
    alt2: '20% increased Cast Speed',
  },
  {
    level: 24,
    name: 'Flammability',
    support: 'Active',
    default: 'Ignite on Cursed enemies has 10% increased Duration',
    alt1: 'Curses inflicted by this Skill have +5 to maximum Doom',
    alt2: 'Hits against Cursed Enemies have +20% chance to Ignite',
  },
  {
    level: 12,
    name: 'Flesh Offering',
    support: 'Active',
    default: '10% increased Skill Effect Duration',
    alt1: 'Grants Minions 0.4% of Damage Leeched as Life',
    alt2: 'Grants Minions 10% increased Attack Speed',
  },
  {
    level: 16,
    name: 'Flesh and Stone',
    support: 'Active',
    default: '10% increased Cooldown Recovery Rate',
    alt1: 'Buff grants 10% increased Evasion Rating and Armour',
    alt2: 'Buff grants 20% increased Damage if youve changed Stance recently',
  },
  {
    level: 10,
    name: 'Flicker Strike',
    support: 'Active',
    default: '5% chance to gain a Frenzy Charge on Hit',
    alt1: '60% increased Cooldown Recovery Rate',
    alt2: '20% increased teleport range',
  },
  {
    level: 1,
    name: 'Freezing Pulse',
    support: 'Active',
    default: '40% increased Projectile Speed',
    alt1: 'Deals 80% of Damage, Projetiles gain Damage over time, dealing up to 60% more Damage by the time they dissipate',
    alt2: 'Cannot Pierce Enemies',
  },
  {
    level: 16,
    name: 'Frenzy',
    support: 'Active',
    default: '10% increased Attack Speed',
    alt1: 'Fires an additional Projectile',
    alt2: 'Targets 1 additional nearby Enemy',
    alt3: '5% increased Damage with Ailments per Frenzy Charge',
  },
  {
    level: 1,
    name: 'Frost Blades',
    support: 'Active',
    default: '20% increased Projectile Speed',
    alt1: '20% increased Damage, Fires 2 additional Projectiles',
    alt2: '20% increased Duration of Cold Ailments',
  },
  {
    level: 4,
    name: 'Frost Bomb',
    support: 'Active',
    default: '20% increased Cold Damage',
    alt1: '10% chance to Freeze enemies',
    alt2: '20% increased Area of Effect',
    alt3: '20% less Skill Effect Duration, 20% increased Cooldown Recovery Rate',
  },
  {
    level: 34,
    name: 'Frost Shield',
    support: 'Active',
    default: '20% increased Effect of Cold Ailments',
    alt1: '20% increased Area of Effect',
    alt2: '10% of Damage dealt to you or Allies in Area with Hits by Enemies in Area is taken from Frost Shields Life before your Life or Energy Shield',
    alt3: 'Frost Shield Regenerates 0.2% of its Life per second'
  },
  {
    level: 4,
    name: 'Frost Wall',
    support: 'Active',
    default: '20% increased Skill Effect Duration',
    alt1: '60% increased Damage',
    alt2: 'Freezes enemies as though dealing 100% more Damage',
  },
  {
    level: 24,
    name: 'Frostbite',
    support: 'Active',
    default: 'Freezes on Cursed enemies have 20% increased Duration',
    alt1: 'Curses inflicted by this Skill have +5 to maximum Doom',
    alt2: 'Hits against Cursed Enemies have +20% chance to Freeze',
  },
  {
    level: 4,
    name: 'Frostblink',
    support: 'Active',
    default: '20% increased Effect of Cold Ailments',
    alt1: '20% increased Area of Effect',
    alt2: '0% increased Cooldown Recovery Rate for each Normal or Magic Enemy in Area, 40% increased Cooldown Recovery Rate for each Rare or Unique Enemy in Area',
  },
  {
    level: 1,
    name: 'Frostbolt',
    support: 'Active',
    default: '20% increased Cold Damage',
    alt1: '100% reduced Damage, 20% chance to inflict Cold Exposure on Hit',
    alt2: '20% less Projectile Speed',
    alt3: '20% chance for Projectiles to Return',
  },
  {
    level: 1,
    name: 'Galvanic Arrow',
    support: 'Active',
    default: '20% increased Projectile Speed',
    alt1: '20% reduced Enemy Stun Threshold',
    alt2: 'Cone Area occurs 80% farther forward',
  },
  {
    level: 24,
    name: 'Generals Cry',
    support: 'Active',
    default: '10% increased Cooldown Recovery Rate',
    alt1: '40% increased Warcry Speed',
    alt2: 'Mirage Warriors have 40% increased Movement Speed',
  },
  {
    level: 28,
    name: 'Glacial Cascade',
    support: 'Active',
    default: '20% increased Damage',
    alt1: '10% increased Area of Effect',
    alt2: '20% reduced Area of Effect, Final Burst Deals 40% more Damage',
  },
  {
    level: 1,
    name: 'Glacial Hammer',
    support: 'Active',
    default: '40% increased Duration of Cold Ailments',
    alt1: '10% increased Attack Speed',
    alt2: '20% increased Area of Effect',
  },
  {
    level: 24,
    name: 'Grace',
    support: 'Active',
    default: '40% increased Area of Effect',
    alt1: 'You and nearby Allies have 10% chance to avoid Elemental Ailments',
    alt2: 'You and nearby Allies have 4% chance to Avoid Chaos Damage from Hits',
  },
  {
    level: 1,
    name: 'Ground Slam',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '20% increased Stun Duration on enemies, 10% increased Attack Speed',
    alt2: '60% increased Area of Effect, 40% reduced angle',
  },
  {
    level: 24,
    name: 'Haste',
    support: 'Active',
    default: '40% increased Area of Effect',
    alt1: 'You and nearby Allies have 10% increased Totem Placement speed',
    alt2: 'You and nearby Allies have 10% increased Projectile Speed',
    alt3: 'Buffs on You and nearby Allies expire 20% faster',
  },
  {
    level: 24,
    name: 'Hatred',
    support: 'Active',
    default: '40% increased Area of Effect',
    alt1: 'You and nearby Allies have 20% increased Chill and Freeze Duration',
    alt2: 'You and nearby Allies have 20% increased Movement Speed while on Chilled Ground',
  },
  {
    level: 1,
    name: 'Heavy Strike',
    support: 'Active',
    default: '20% increased Stun Duration on enemies',
    alt1: '20% increased Damage, 20% increased Knockback Distance',
    alt2: '100% reduced Knockback Distance',
  },
  {
    level: 16,
    name: 'Herald of Agony',
    support: 'Active',
    default: '20% increased Minion Movement Speed',
    alt1: 'Minions deal 40% less Damage, Agony Crawler has 20% chance to inflict Withered for 2 seconds on Hit',
    alt2: 'Grants 20% chance to Poison on Hit',
  },
  {
    level: 16,
    name: 'Herald of Ash',
    support: 'Active',
    default: 'Buff grants 15% increased Fire Damage',
    alt1: '20% reduced Area of Effect, 60% increased Burning Damage',
    alt2: '20% increased Area of Effect',
  },
  {
    level: 16,
    name: 'Herald of Ice',
    support: 'Active',
    default: 'Buff grants 15% increased Cold Damage',
    alt1: '10% increased Area of Effect',
    alt2: 'Buff grants 10% chance to Freeze',
  },
  {
    level: 16,
    name: 'Herald of Purity',
    support: 'Active',
    default: '20% increased Minion Movement Speed',
    alt1: 'Minions have 10% chance to Taunt on Hit',
    alt2: 'Summoned Sentinels have 20% increased Cooldown Recovery Rate',
  },
  {
    level: 16,
    name: 'Herald of Thunder',
    support: 'Active',
    default: 'Buff grants 15% increased Lightning Damage',
    alt1: '20% increased Skill Effect Duration',
    alt2: 'Buff grants 10% increased Damage taken, Buff grants 30% increased Damage',
  },
  {
    level: 28,
    name: 'Hexblast',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '10% increased Cast Speed',
    alt2: '40% increased Damage with Ailments, 20% increased Effect of non-Damaging Ailments on Enemies',
    alt3: 'Hexblast has 10% chance to not remove a Hex',
  },
  {
    level: 4,
    name: 'Holy Flame Totem',
    support: 'Active',
    default: '20% increased Projectile Speed',
    alt1: 'Fires an additional Projectile',
    alt2: '20% of Physical Damage Converted to Fire Damage',
    alt3: '20% increased Totem Duration, 20% increased Totem Placement speed',
  },
  {
    level: 28,
    name: 'Ice Crash',
    support: 'Active',
    default: '20% increased Damage',
    alt1: '10% chance to Freeze enemies',
    alt2: '60% increased Damage with Ailments',
    alt3: 'Third Stage deals 30% more Damage, First Stage deals 40% less Damage',
  },
  {
    level: 12,
    name: 'Ice Nova',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '30% increased Damage with Hits against Chilled Enemies',
    alt2: '10% increased Cast Speed',
    alt3: '10% increased Effect of Chill'
  },
  {
    level: 1,
    name: 'Ice Shot',
    support: 'Active',
    default: '20% increased Cold Damage',
    alt1: '10% increased Area of Effect',
    alt2: '20% of Physical Damage Converted to Cold Damage',
  },
  {
    level: 12,
    name: 'Ice Spear',
    support: 'Active',
    default: '40% increased Projectile Speed',
    alt1: 'Projectiles Pierce 2 additional Targets',
    alt2: '20% increased Cold Damage',
    alt3: 'Travels 20% reduced distance before changing forms'
  },
  {
    level: 28,
    name: 'Ice Trap',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: 'Penetrates 5% Cold Resistance',
    alt2: 'Freezes enemies as though dealing 100% more Damage',
  },
  {
    level: 12,
    name: 'Icicle Mine',
    support: 'Active',
    default: '20% increased Projectile Speed',
    alt1: 'Fires 2 additional Projectiles',
    alt2: '20% increased Critical Strike Chance',
  },
  {
    level: 34,
    name: 'Immortal Call',
    support: 'Active',
    default: '20% increased Skill Effect Duration',
    alt1: '20% increased Cooldown Recovery Rate',
    alt2: '2% less Elemental Damage taken per Endurance Charge removed, 2% more Physical Damage taken per Endurance Charge removed',
  },
  {
    level: 12,
    name: 'Incinerate',
    support: 'Active',
    default: '20% increased Fire Damage',
    alt1: '10% increased Area of Effect',
    alt2: '4% more Damage with Hits and Ailments for each stage, Final wave deals 200% less Damage with Hits, Final wave deals 200% less Damage with Ignite',
  },
  {
    level: 12,
    name: 'Infernal Blow',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: 'Explosion has 20% chance to apply Uncharged Debuff on Hit',
    alt2: '60% increased Burning Damage, 20% chance to Ignite enemies',
    alt3: '80% increased Skill Effect Duration',
  },
  {
    level: 24,
    name: 'Infernal Cry',
    support: 'Active',
    default: '20% increased Area of Effect',
    alt1: '40% increased Warcry Speed',
    alt2: 'Exerted Attacks deal 10% increased Damage',
    alt3: '20% chance to Cover Enemies in Ash on Hit'
  },
  {
    level: 10,
    name: 'Intimidating Cry',
    support: 'Active',
    default: '10% increased Cooldown Recovery Rate',
    alt1: '40% increased Warcry Speed',
    alt2: 'Exerted Attacks Overwhelm 10% of Physical Damage Reduction',
    alt3: 'Exerted Attacks deal 10% increased Damage',
  },
  {
    level: 28,
    name: 'Kinetic Blast',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: 'Projectiles Pierce 2 additional Targets',
    alt2: 'Projectiles gain 30% increased Area of Effect after Forking',
  },
  {
    level: 1,
    name: 'Kinetic Bolt',
    support: 'Active',
    default: '20% increased Projectile Speed',
    alt1: 'Increases and Reductions to Cast Speed apply to Attack Speed',
    alt2: '+2 Mana gained for each Enemy hit',
  },
  {
    level: 12,
    name: 'Lacerate',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '20% increased Physical Damage',
    alt2: '20% increased Bleeding Duration',
  },
  {
    level: 28,
    name: 'Lancing Steel',
    support: 'Active',
    default: '20% increased Impale Effect',
    alt1: 'Clusters have 30% increased Projectile targeting range',
    alt2: 'Projectiles deal up to 40% increased Damage with Hits and Ailments at the start of their movement, lowering this bonus as they travel farther',
    alt3: '10% chance to Impale Enemies on Hit',
  },
  {
    level: 10,
    name: 'Leap Slam',
    support: 'Active',
    default: '20% increased Stun Duration on enemies',
    alt1: '20% increased Area of Effect',
    alt2: '20% increased Damage',
    alt3: '10% increased Attack Speed',
  },
  {
    level: 12,
    name: 'Lightning Arrow',
    support: 'Active',
    default: '20% chance to Shock enemies',
    alt1: '20% increased Area of Effect',
    alt2: '20% of Physical Damage Converted to Lightning Damage',
    alt3: '20% chance to Hit an additional Enemy',
  },
  {
    level: 28,
    name: 'Lightning Spire Trap',
    support: 'Active',
    default: '20% chance to Shock enemies',
    alt1: '20% less Skill Effect Duration, 60% increased Cooldown Recovery Rate',
    alt2: '10% chance to Hinder Enemies on Hit, with 30% reduced Movement Speed',
  },
  {
    level: 12,
    name: 'Lightning Strike',
    support: 'Active',
    default: '20% increased Projectile Speed',
    alt1: '20% increased Damage, Projectiles Pierce 2 additional Targets',
    alt2: 'Fires 2 additional Projectiles',
    alt3: '20% of Physical Damage Converted to Lightning Damage',
  },
  {
    level: 1,
    name: 'Lightning Tendrils',
    support: 'Active',
    default: '20% increased Lightning Damage',
    alt1: '10% increased Area of Effect',
    alt2: '10% increased Cast Speed',
    alt3: 'Deals 60% of Damage, Stronger Pulses deal 200% more Damage with Hits and Ailments',
  },
  {
    level: 12,
    name: 'Lightning Trap',
    support: 'Active',
    default: '20% increased Lightning Damage',
    alt1: '10% increased Effect of Lightning Ailments, 20% increased Projectile Speed',
    alt2: '20% chance for Projectiles to Return',
  },
  {
    level: 10,
    name: 'Lightning Warp',
    support: 'Active',
    default: '20% increased Cast Speed',
    alt1: '20% increased Area of Effect',
    alt2: '60% increased Damage, 20% increased Duration',
    alt3: '10% less Duration',
  },
  {
    level: 1,
    name: 'Magma Orb',
    support: 'Active',
    default: '20% increased Damage',
    alt1: '10% increased Area of Effect',
    alt2: '20% increased Projectile Speed',
    alt3: '10% chance to Detonate for Double Damage instead of Chaining',
  },
  {
    level: 24,
    name: 'Malevolence',
    support: 'Active',
    default: '40% increased Area of Effect',
    alt1: 'You and nearby allies have 10% increased Skill Effect Duration',
    alt2: 'You and nearby Allies deal 10% increased Damage with Ailments',
  },
  {
    level: 10,
    name: 'Mirror Arrow',
    support: 'Active',
    default: '30% increased Arrow Speed',
    alt1: 'Minions have 20% increased Duration',
    alt2: '60% increased Minion Maximum Life',
    alt3: '+2 Cooldown Uses',
  },
  {
    level: 4,
    name: 'Molten Shell',
    support: 'Active',
    default: '20% increased Skill Effect Duration',
    alt1: 'Buff can take additional Damage equal to 5% of your Armour',
    alt2: 'Reflected Damage Penetrates 20% of Enemy Fire Resistance',
  },
  {
    level: 1,
    name: 'Molten Strike',
    support: 'Active',
    default: '20% increased Fire Damage',
    alt1: '20% increased Projectile Speed',
    alt2: '+2 to Melee Strike Range',
    alt3: '40% increased Damage over Time',
  },
  {
    level: 4,
    name: 'Orb of Storms',
    support: 'Active',
    default: '20% increased Lightning Damage',
    alt1: 'Beams Split towards 2 additional targets',
    alt2: '20% less Skill Effect Duration, 20% increased Cast Speed',
  },
  {
    level: 28,
    name: 'Penance Brand',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '20% of Physical Damage Converted to Fire Damage',
    alt2: '20% chance to Shock enemies',
  },
  {
    level: 1,
    name: 'Perforate',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '10% chance to Impale Enemies on Hit',
    alt2: '20% chance to cause Bleeding',
    alt3: 'Creates 2 additional Spikes if youve changed Stance Recently, Creates 1 fewer Spikes',
  },
  {
    level: 28,
    name: 'Pestilent Strike',
    support: 'Active',
    default: '+10% to Damage over Time Multiplier for Poison',
    alt1: '20% increased Area of Effect',
    alt2: '20% increased Skill Effect Duration',
    alt3: '20% of Physical Damage Converted to Chaos Damage',
  },
  {
    level: 34,
    name: 'Phase Run',
    support: 'Active',
    default: 'Buff grants 10% increased Movement Speed',
    alt1: '20% increased Skill Effect Duration',
    alt2: '10% chance not to replace the Buff when you use a Skill',
  },
  {
    level: 24,
    name: 'Plague Bearer',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: 'You have 10% Movement Speed while Infecting',
    alt2: '10% reduced Chaos Damage taken while Incubating',
  },
  {
    level: 24,
    name: 'Poachers Mark',
    support: 'Active',
    default: 'Cursed Enemies have a 5% chance to grant a Frenzy Charge when Hit',
    alt1: 'Cursed enemies take 4% increased Damage',
    alt2: 'Cursed enemies have -5% to Physical Damage Reduction',
  },
  {
    level: 12,
    name: 'Power Siphon',
    support: 'Active',
    default: '20% increased Damage',
    alt1: 'Fires an additional Projectile',
    alt2: '+20% to Damage over Time Multiplier for Ailments from Critical Strikes',
  },
  {
    level: 10,
    name: 'Precision',
    support: 'Active',
    default: '40% increased Area of Effect',
    alt1: '10% reduced Mana Reserved',
    alt2: 'You and nearby Allies deal 10% increased Damage, You and nearby Allies have 10% less Area of Effect',
  },
  {
    level: 24,
    name: 'Pride',
    support: 'Active',
    default: '40% increased Area of Effect',
    alt1: 'Attack Hits againts nearby Enemies have 10% chance to inflict Bleeding',
    alt2: 'Nearby Enemies have -5% to Physical Damage Reduction',
  },
  {
    level: 4,
    name: 'Puncture',
    support: 'Active',
    default: 'Bleeding inflicted by this Skill deals Damage 10% faster',
    alt1: 'Projectiles Pierce 2 additional Targets',
    alt2: 'Targets 2 additional nearby Enemies',
    alt3: '10% chance to Maim on Hit',
  },
  {
    level: 24,
    name: 'Punishment',
    support: 'Active',
    default: '10% increased Effect of Curse',
    alt1: 'Curse has 40% increased Doom gain rate',
    alt2: '20% increased Area of Effect of Curses',
  },
  {
    level: 1,
    name: 'Purifying Flame',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '10% chance to also create Consecrated Ground around you',
    alt2: 'Consecrated Ground applies 5% increased Damage taken to Enemies',
    alt3: '20% increased Effect of Consecrated Ground',
  },
  {
    level: 24,
    name: 'Purity of Elements',
    support: 'Active',
    default: '40% increased Area of Effect',
    alt1: 'You and nearby Allies have 10% chance to avoid Elemental Ailments',
    alt2: 'Your and nearby Allies Damage Penetrates 4% Elemental Resistances',
  },
  {
    level: 24,
    name: 'Purity of Fire',
    support: 'Active',
    default: '40% increased Area of Effect',
    alt1: 'You and nearby Allies have 20% chance to avoid being Ignited',
    alt2: 'Your and nearby Allies Damage Penetrates 4% Fire Resistance',
  },
  {
    level: 24,
    name: 'Purity of Ice',
    support: 'Active',
    default: '40% increased Area of Effect',
    alt1: 'You and nearby Allies have 20% chance to avoid being Frozen',
    alt2: 'Your and nearby Allies Damage Penetrates 4% Cold Resistance',
  },
  {
    level: 24,
    name: 'Purity of Lightning',
    support: 'Active',
    default: '40% increased Area of Effect',
    alt1: 'You and nearby Allies have 20% chance to avoid being Shocked',
    alt2: 'Your and nearby Allies Damage Penetrates 4% Lightning Resistance',
  },
  {
    level: 28,
    name: 'Pyroclast Mine',
    support: 'Active',
    default: '20% increased Area of Effect',
    alt1: '100% increased Burning Damage, 20% chance to Ignite enemies',
    alt2: '20% increased effect of Aura',
    alt3: '40% increased Damage if firing at least 7 Projectiles',
  },
  {
    level: 12,
    name: 'Rain of Arrows',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '5% chance to fire an additional sequence of arrows',
    alt2: 'Fires 4 additional Arrows',
    alt3: '10% chance to Maim on Hit',
  },
  {
    level: 28,
    name: 'Raise Spectre',
    support: 'Active',
    default: '20% increased Minion Movement Speed',
    alt1: '20% increased Minion Maximum Life, Minions deal 20% increased Melee Damage',
    alt2: 'Minions have 10% reduced Enemy Stun Threshold',
    alt3: 'Minions are Created with maximum Frenzy Charges',
  },
  {
    level: 1,
    name: 'Raise Zombie',
    support: 'Active',
    default: '20% increased Minion Movement Speed',
    alt1: '20% increased Minion Maximum Life, Raised Zombies Slam Attack has 40% increased Cooldown Recovery Rate',
    alt2: 'Minions Regenerate 2% of Life per second',
    alt3: 'Minions gain 10% of Physical Damage as Extra Chaos Damage, Minions take Chaos Damage equal to 20% of their Life over one second when Raised',
  },
  {
    level: 24,
    name: 'Rallying Cry',
    support: 'Active',
    default: '20% increased Area of Effect',
    alt1: '40% increased Warcry Speed',
    alt2: 'Buff has 40% more Effect on your Minions',
    alt3: 'Exerted Attacks deal 10% increased Damage',
  },
  {
    level: 12,
    name: 'Reave',
    support: 'Active',
    default: '10% increased Attack Speed',
    alt1: '100% of Physical Damage converted to a random Element',
    alt2: '20% chance to cause Bleeding',
    alt3: '+2 to maximum Stages',
  },
  {
    level: 4,
    name: 'Reckoning',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '40% chance to Debilitate Enemies for 1 second on Hit',
    alt2: '20% increased Cooldown Recovery Rate',
    alt3: '20% increased Damage',
  },
  {
    level: 4,
    name: 'Rejuvenation Totem',
    support: 'Active',
    default: '60% increased Aura Area of Effect',
    alt1: '100% increased Totem Duration',
    alt2: '60% increased effect of Aura',
  },
  {
    level: 16,
    name: 'Righteous Fire',
    support: 'Active',
    default: '20% increased Burning Damage',
    alt1: '10% increased Area of Effect',
    alt2: 'Buff Grants 20% increased Spell Damage',
  },
  {
    level: 4,
    name: 'Riposte',
    support: 'Active',
    default: '20% increased Damage',
    alt1: '20% increased Cooldown Recovery Rate',
    alt2: '20% chance to gain Onslaught for 4 seconds on Hit',
  },
  {
    level: 12,
    name: 'Scorching Ray',
    support: 'Active',
    default: '10% increased beam length',
    alt1: '20% increased Skill Effect Duration',
    alt2: '40% less Skill Effect Duration, 40% increased Cast Speed',
  },
  {
    level: 28,
    name: 'Scourge Arrow',
    support: 'Active',
    default: '20% increased Projectile Speed',
    alt1: 'Each Spore Pod fires 2 Thorn Arrows',
    alt2: '20% increased Damage',
    alt3: '20% chance to Poison on Hit',
  },
  {
    level: 12,
    name: 'Searing Bond',
    support: 'Active',
    default: '20% increased totem life',
    alt1: '40% increased Totem Duration',
    alt2: '20% increased Damage',
    alt3: '+2 to maximum number of Summoned Totems',
  },
  {
    level: 16,
    name: 'Seismic Cry',
    support: 'Active',
    default: '10% increased Cooldown Recovery Rate',
    alt1: '40% increased Warcry Speed',
    alt2: 'Exerted Attacks have a 40% chance to Knock Enemies Back on Hit',
    alt3: 'Exerted Attacks deal 10% increased Damage',
  },
  {
    level: 28,
    name: 'Seismic Trap',
    support: 'Active',
    default: '20% increased Physical Damage',
    alt1: '10% increased Area of Effect',
    alt2: '20% increased Cooldown Recovery Rate',
    alt3: '60% reduced Cast Speed, 100% increased Damage',
  },
  {
    level: 12,
    name: 'Shattering Steel',
    support: 'Active',
    default: '20% increased Impale Effect',
    alt1: '10% increased Area of Effect, 20% increased Projectile Speed',
    alt2: 'Fires an additional Projectile',
    alt3: '30% increased Projectile Speed',
  },
  {
    level: 10,
    name: 'Shield Charge',
    support: 'Active',
    default: '20% increased Movement Speed',
    alt1: '20% increased Damage',
    alt2: '20% more Damage with Hits at Maximum Charge Distance',
  },
  {
    level: 28,
    name: 'Shock Nova',
    support: 'Active',
    default: '40% increased Shock Duration on enemies',
    alt1: 'Ring has 40% chance to Shock, Ring Shocks as if dealing 100% more Damage',
    alt2: '20% increased Lightning Damage',
  },
  {
    level: 28,
    name: 'Shockwave Totem',
    support: 'Active',
    default: '20% increased totem life',
    alt1: '10% increased Cast Speed, 20% increased Totem Placement speed',
    alt2: '40% of Physical Damage Converted to Cold Damage',
    alt3: '20% chance to Knock Enemies Back on hit',
  },
  {
    level: 4,
    name: 'Shrapnel Ballista',
    support: 'Active',
    default: '20% increased Projectile Speed',
    alt1: 'Chains +2 Times',
    alt2: 'Projectiles Pierce 2 additional Targets',
    alt3: '10% increased Attack Speed',
  },
  {
    level: 12,
    name: 'Siege Ballista',
    support: 'Active',
    default: '20% increased Projectile Damage',
    alt1: 'Fires 2 additional Projectiles, 20% reduced Attack Speed',
    alt2: '20% increased Projectile Speed',
    alt3: '20% chance to Impale Enemies on Hit',
  },
  {
    level: 34,
    name: 'Sigil of Power',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: 'Maximum -1 Stages',
    alt2: 'Buff Grants 20% chance to Shock enemies',
    alt3: '10% reduced Mana Cost of your Skills while in Area, Buff Grants 20% increased Spell Damage',
  },
  {
    level: 10,
    name: 'Siphoning Trap',
    support: 'Active',
    default: '20% increased Effect of Cold Ailments',
    alt1: '20% increased Skill Effect Duration',
    alt2: 'Applies beams to the closest 2 Enemies',
    alt3: 'Regenerate 0.4% of Energy Shield per second for each affected Enemy',
  },
  {
    level: 1,
    name: 'Smite',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '20% increased Skill Effect Duration',
    alt2: '20% increased Lightning Damage',
    alt3: 'Aura grants 5% increased Attack and Cast Speed',
  },
  {
    level: 10,
    name: 'Smoke Mine',
    support: 'Active',
    default: '40% increased Area of Effect',
    alt1: '20% increased Skill Effect Duration',
    alt2: 'Buff grants 10% increased Attack and Cast Speed',
  },
  {
    level: 24,
    name: 'Snipers Mark',
    support: 'Active',
    default: 'Cursed enemies take 5% increased Damage from Projectile Hits',
    alt1: 'Curse Skills have 20% increased Cast Speed',
    alt2: 'Hits on Cursed Enemies have an additional 40% chance to Knockback',
  },
  {
    level: 28,
    name: 'Soulrend',
    support: 'Active',
    default: '20% increased Chaos Damage',
    alt1: '20% increased Area of Effect',
    alt2: '20% increased Skill Effect Duration',
    alt3: '100% increased Damage with Hits',
  },
  {
    level: 1,
    name: 'Spark',
    support: 'Active',
    default: '20% increased Projectile Speed',
    alt1: 'Projectiles Pierce 2 additional Targets',
    alt2: 'Fires 2 additional Projectiles',
    alt3: '40% of Lightning Damage Converted to Chaos Damage',
  },
  {
    level: 12,
    name: 'Spectral Shield Throw',
    support: 'Active',
    default: '40% increased Projectile Speed',
    alt1: '20% increased Damage',
    alt2: '10% increased Attack Speed',
    alt3: '+20% to Critical Strike Multiplier per 100 Maximum Energy Shield on Shield',
  },
  {
    level: 1,
    name: 'Spectral Throw',
    support: 'Active',
    default: '10% increased Attack Speed',
    alt1: '20% increased Projectile Speed',
    alt2: 'Fires an additional Projectile, 10% reduced Projectile Speed',
  },
  {
    level: 24,
    name: 'Spellslinger',
    support: 'Active',
    default: 'Supported Skills deal 20% increased Spell Damage',
    alt1: 'Supported Skills have 20% chance to Freeze, Shock and Ignite',
    alt2: 'Supported Skills have 40% reduced Cooldown Recovery Rate, Supported Skills have Added Spell Damage equal to 40% of Damage of Equipped Wand If two Wands are Equipped, each contributes half as much Added Damage',
  },
  {
    level: 12,
    name: 'Spirit Offering',
    support: 'Active',
    default: '10% increased Skill Effect Duration',
    alt1: '40% increased Cast Speed',
    alt2: 'Minions gain +20% to all Elemental Resistances',
  },
  {
    level: 1,
    name: 'Split Arrow',
    support: 'Active',
    default: '10% increased Attack Speed',
    alt1: 'Fires an additional Arrow',
    alt2: '20% increased Damage',
  },
  {
    level: 1,
    name: 'Splitting Steel',
    support: 'Active',
    default: '20% increased Impale Effect',
    alt1: '10% chance to inflict an additional Impale when this Skill inflcits Impale',
    alt2: '10% increased Area of Effect, 20% increased Projectile Speed',
    alt3: 'Grants Minions 40% increased Damage',
  },
  {
    level: 12,
    name: 'Static Strike',
    support: 'Active',
    default: '20% increased Skill Effect Duration',
    alt1: '20% increased Damage',
    alt2: 'Chains +1 Times, 40% reduced Damage',
    alt3: '20% increased Beam frequency, 20% reduced Area of Effect',
  },
  {
    level: 4,
    name: 'Steelskin',
    support: 'Active',
    default: '10% increased Cooldown Recovery Rate',
    alt1: 'Steelskin Buff can take 10% increased amount of Damage',
    alt2: 'Buff grants +20% to all Resistances',
  },
  {
    level: 12,
    name: 'Storm Brand',
    support: 'Active',
    default: '10% increased Cast Speed',
    alt1: '10% increased Area of Effect',
    alt2: '20% chance to Chain an additional time',
    alt3: '20% increased Effect of Shock',
  },
  {
    level: 12,
    name: 'Storm Burst',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '10% increased Skill Effect Duration',
    alt2: '40% reduced Explosion Area of Effect, 40% increased Area of Effect while Channelling',
  },
  {
    level: 12,
    name: 'Storm Call',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '40% reduced Cast Speed, 40% increased Area of Effect',
    alt2: '10% reduced Skill Effect Duration',
    alt3: '5% chance for Lightning to Strike the Marker when Cast',
  },
  {
    level: 28,
    name: 'Stormbind',
    support: 'Active',
    default: '10% increased Cast Speed',
    alt1: '10% increased Cast Speed, 20% increased Effect of Shock',
    alt2: 'Runes have 10% increased Area of Effect for each time theyve been Improved',
    alt3: '20% more Damage, Runes deal 60% less Damage with Hits and Ailments for each time they have been Improved',
  },
  {
    level: 1,
    name: 'Stormblast Mine',
    support: 'Active',
    default: '10% chance to Shock enemies',
    alt1: '10% increased Effect of Lightning Ailments, 10% increased Area of Effect',
    alt2: '20% increased effect of Aura',
    alt3: '20% increased Lightning Damage',
  },
  {
    level: 34,
    name: 'Summon Carrion Golem',
    support: 'Active',
    default: 'Minions deal 20% increased Damage',
    alt1: '20% increased Minion Maximum Life, 20% increased Buff Effect',
    alt2: 'Summoned Golems have 20% increased Cooldown Recovery Rate',
  },
  {
    level: 34,
    name: 'Summon Chaos Golem',
    support: 'Active',
    default: 'Minions deal 20% increased Damage',
    alt1: '20% increased Minion Maximum Life, 20% increased Buff Effect',
    alt2: 'Summoned Golems have 20% increased Cooldown Recovery Rate',
  },
  {
    level: 34,
    name: 'Summon Flame Golem',
    support: 'Active',
    default: 'Minions deal 20% increased Damage',
    alt1: '20% increased Minion Maximum Life, 20% increased Buff Effect',
    alt2: 'Summoned Golems have 20% increased Cooldown Recovery Rate',
  },
  {
    level: 4,
    name: 'Summon Holy Relic',
    support: 'Active',
    default: 'Minions have 10% increased Area of Effect',
    alt1: '60% increased Minion Maximum Life',
    alt2: 'Summoned Holy Relics have 20% increased Cooldown Recovery Rate',
  },
  {
    level: 34,
    name: 'Summon Ice Golem',
    support: 'Active',
    default: 'Minions deal 20% increased Damage',
    alt1: '20% increased Minion Maximum Life, 20% increased Buff Effect',
    alt2: 'Summoned Golems have 20% increased Cooldown Recovery Rate',
  },
  {
    level: 34,
    name: 'Summon Lightning Golem',
    support: 'Active',
    default: 'Minions deal 20% increased Damage',
    alt1: '20% increased Minion Maximum Life, 20% increased Buff Effect',
    alt2: 'Summoned Golems have 20% increased Cooldown Recovery Rate',
  },
  {
    level: 4,
    name: 'Summon Raging Spirit',
    support: 'Active',
    default: '20% increased Minion Movement Speed',
    alt1: 'Minions have 20% increased Duration',
    alt2: 'Maximum 2 Summoned Raging Spirits',
    alt3: 'Minions cant be Damaged for 2 seconds after being Summoned',
  },
  {
    level: 10,
    name: 'Summon Skeletons',
    support: 'Active',
    default: 'Minions deal 20% increased Damage',
    alt1: 'Minions cant be Damaged for 2 seconds after being Summoned',
    alt2: 'Minions Attacks have 10% chance to Maim Enemies on Hit',
    alt3: '100% chance to Summon a Skeleton Archer instead of a Skeleton Warrior',
  },
  {
    level: 16,
    name: 'Summon Skitterbots',
    support: 'Active',
    default: '40% increased Minion Movement Speed',
    alt1: 'Minions have 20% increased Area of Effect',
    alt2: 'Minions have 10% increased Effect of non-Damaging Ailments on Enemies',
  },
  {
    level: 34,
    name: 'Summon Stone Golem',
    support: 'Active',
    default: 'Minions deal 20% increased Damage',
    alt1: '20% increased Minion Maximum Life, 20% increased Buff Effect',
    alt2: 'Summoned Golems have 20% increased Cooldown Recovery Rate',
  },
  {
    level: 12,
    name: 'Sunder',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: 'Wave has 10% reduced delay between Areas',
    alt2: '20% increased Area of Effect',
    alt3: 'Shockwaves have 20% reduced Area of Effect, Wave has 20% increased Area of Effect',
  },
  {
    level: 12,
    name: 'Sweep',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '10% increased Attack Speed',
    alt2: '2% chance to deal Triple Damage',
    alt3: '20% increased Knockback Distance',
  },
  {
    level: 28,
    name: 'Tectonic Slam',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '60% increased Burning Damage, 20% chance to Ignite enemies',
    alt2: '2% of Fire Damage Leeched as Life',
    alt3: '20% increased Fire Damage',
  },
  {
    level: 16,
    name: 'Tempest Shield',
    support: 'Active',
    default: '20% increased Lightning Damage',
    alt1: 'Chains +2 Times',
    alt2: '+1% Chance to Block Attack Damage while holding a Shield, +1% Chance to Block Spell Damage while holding a Shield',
  },
  {
    level: 24,
    name: 'Temporal Chains',
    support: 'Active',
    default: '10% increased Effect of Curse',
    alt1: 'Curse has 40% increased Doom gain rate',
    alt2: '20% increased Curse Duration',
  },
  {
    level: 28,
    name: 'Tornado Shot',
    support: 'Active',
    default: '20% increased Projectile Damage',
    alt1: '60% of Physical Damage converted to a random Element',
    alt2: '10% increased Attack Speed',
  },
  {
    level: 12,
    name: 'Toxic Rain',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '10% increased Skill Effect Duration',
    alt2: '20% of Physical Damage Converted to Chaos Damage',
    alt3: 'Fires 2 additional Arrows, 20% reduced Debuff Effect',
  },
  {
    level: 10,
    name: 'Unearth',
    support: 'Active',
    default: '10% increased Cast Speed',
    alt1: '20% increased Physical Damage',
    alt2: 'Maximum of 2 corpses allowed',
    alt3: 'Corpses Spawned have 40% increased Maximum Life',
  },
  {
    level: 24,
    name: 'Vengeance',
    support: 'Active',
    default: '10% chance to Trigger this Skill when Hit',
    alt1: '20% increased Cooldown Recovery Rate',
    alt2: '20% increased Damage',
    alt3: '40% chance to gain 1 Rage on Hit',
  },
  {
    level: 12,
    name: 'Venom Gyre',
    support: 'Active',
    default: '20% increased Poison Duration',
    alt1: 'Returning Projectiles deal 20% more Damage',
    alt2: '100% chance to Fire a caught Projectile when Hit',
  },
  {
    level: 4,
    name: 'Vigilant Strike',
    support: 'Active',
    default: '40% increased Fortify duration',
    alt1: '40% increased Area of Effect',
    alt2: '60% increased Cooldown Recovery Rate',
    alt3: '20% increased Damage',
  },
  {
    level: 1,
    name: 'Viper Strike',
    support: 'Active',
    default: '10% increased Attack Speed',
    alt1: '10% increased Poison Duration, 20% of Physical Damage Converted to Chaos Damage',
    alt2: '20% increased Chaos Damage',
    alt3: '10% chance to also Poison a nearby Enemy when you inflict Poison',
  },
  {
    level: 10,
    name: 'Vitality',
    support: 'Active',
    default: '40% increased Area of Effect',
    alt1: 'You and nearby Allies Leech 0.4% of Physical Attack Damage as Life',
    alt2: 'You and nearby Allies deal 20% increased Damage while on Full Life',
  },
  {
    level: 34,
    name: 'Void Sphere',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '40% reduced Skill Effect Duration, 40% increased Cooldown Recovery Rate',
    alt2: '60% of Physical Damage Converted to Cold Damage',
    alt3: 'Void Sphere has 10% increased Pulse Frequency',
  },
  {
    level: 12,
    name: 'Volatile Dead',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '20% increased Fire Damage',
    alt2: '20% increased Orb Movement Speed',
  },
  {
    level: 28,
    name: 'Vortex',
    support: 'Active',
    default: '10% increased Area of Effect',
    alt1: '20% increased Cold Damage',
    alt2: '20% less Skill Effect Duration, 20% increased Cooldown Recovery Rate',
    alt3: '40% increased Damage when Cast on Frostbolt',
  },
  {
    level: 24,
    name: 'Vulnerability',
    support: 'Active',
    default: 'Attacks Hits against Cursed Enemies have 10% chance to inflict Bleeding',
    alt1: '10% increased Effect of Curse',
    alt2: 'Attack Hits have 10% chance to Maim Cursed Enemies for 4 seconds',
  },
  {
    level: 4,
    name: 'War Banner',
    support: 'Active',
    default: '10% increased effect of Aura',
    alt1: '60% less Skill Effect Duration, You and nearby allies gain 10% increased Accuracy Rating',
    alt2: '20% increased Skill Effect Duration',
  },
  {
    level: 24,
    name: 'Warlords Mark',
    support: 'Active',
    default: 'Cursed Enemies have a 5% chance to grant an Endurance Charge when Hit',
    alt1: 'Cursed enemies take 4% increased Damage',
    alt2: 'Cursed Enemies grant 2 Rage Regenerated over 1 second when Stunned',
  },
  {
    level: 16,
    name: 'Wave of Conviction',
    support: 'Active',
    default: '20% increased Elemental Damage',
    alt1: '20% increased Area of Effect',
    alt2: '20% increased Skill Effect Duration',
    alt3: '20% of Physical Damage Converted to Cold Damage'
  },
  {
    level: 10,
    name: 'Whirling Blades',
    support: 'Active',
    default: '10% increased Attack Speed',
    alt1: '60% increased Damage',
    alt2: '200% increased Evasion Rating while Moving',
  },
  {
    level: 28,
    name: 'Wild Strike',
    support: 'Active',
    default: '20% increased Elemental Damage',
    alt1: '20% increased Area of Effect',
    alt2: 'Fires 2 additional Projectiles',
    alt3: '20% increased Chaining range',
  },
  {
    level: 28,
    name: 'Winter Orb',
    support: 'Active',
    default: '10% increased Cast Speed',
    alt1: '10% increased Area of Effect',
    alt2: '20% increased Skill Effect Duration',
    alt3: '40% increased Projectile Speed',
  },
  {
    level: 12,
    name: 'Wintertide Brand',
    support: 'Active',
    default: '+10% to Cold Damage over Time Multiplier',
    alt1: '10% increased Area of Effect',
    alt2: '40% increased Skill Effect Duration, 40% reduced Cast Speed',
  },
  {
    level: 10,
    name: 'Wither',
    support: 'Active',
    default: '20% increased Skill Effect Duration',
    alt1: 'Hindered Enemies deal 4% reduced Chaos Damage',
    alt2: '100% chance to apply an additional Withered Debuff if you Cast this spell yourself',
  },
  {
    level: 10,
    name: 'Withering Step',
    support: 'Active',
    default: '10% increased Effect of Elusive from this Skill',
    alt1: 'Inflicts 2 Withered Debuffs the first time each Enemy enters the Area',
    alt2: '20% chance not to remove Buff on Skill use',
  },
  {
    level: 24,
    name: 'Wrath',
    support: 'Active',
    default: '40% increased Area of Effect',
    alt1: '5% increased effect of Aura',
    alt2: '2% reduced Mana Reserved',
  },
  {
    level: 24,
    name: 'Zealotry',
    support: 'Active',
    default: '40% increased Area of Effect',
    alt1: 'You and nearby Allies have +5% to Critical Strike Multiplier',
    alt2: 'You and nearby Allies Regenerate 0.40% of Life per second',
  }
];

@Component({
  selector: 'app-skills',
  templateUrl: './skills.component.html',
  styleUrls: ['./skills.component.scss']
})
export class SkillsComponent implements OnInit {
  displayedColumns: string[] = ['level', 'name', 'support', 'default', 'alt1', 'alt2', 'alt3'];
  dataSource = DATA;

  constructor() { }

  ngOnInit(): void {
  }
}
