import { SkillGemList } from '../skills.component';

export const supportGemList: SkillGemList[] = [
    { 
        level: 31, 
        name: 'Added Chaos Damage',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Chaos Damage',
        alt1: 'Anomalous : Supported Skills Penetrate 5% Chaos Resistance',
        alt2: 'Divergent : Supported Skills have 20% of Physical Damage Converted to Chaos Damage',
    },
    { 
        level: 8, 
        name: 'Added Cold Damage',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Cold Damage',
        alt1: 'Anomalous : Supported Skills have 10% increased Attack and Cast Speed',
        alt2: 'Divergent : Supported Skills have 20% of Physical Damage Converted to Cold Damage',
    },
    { 
        level: 8, 
        name: 'Added Fire Damage',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Fire Damage',
        alt1: 'Anomalous : Supported Skills deal 20% reduced Fire Damage, Supported Skills have +20% to Fire Damage over Time Multiplier',
        alt2: 'Divergent : Supported Skills have 20% of Physical Damage Converted to Fire Damage',
    },
    { 
        level: 8, 
        name: 'Added Lightning Damage',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Lightning Damage',
        alt1: 'Anomalous : Supported Skills have 30% increased Critical Strike Chance',
        alt2: 'Divergent : Supported Skills have 20% of Physical Damage Converted to Lightning Damage',
    },
    { 
        level: 8, 
        name: 'Additional Accuracy',
        support: 'Support', 
        default: 'Supported Skills have 20% increased Accuracy Rating',
        alt1: 'Anomalous : Supported Skills have +20% to Critical Strike Multiplier',
        alt2: 'Divergent : Supported Skills deal 4% increased Attack damage per 1000 Accuracy Rating',
    },
    { 
        level: 31, 
        name: 'Advanced Traps',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Trap Damage',
        alt1: 'Anomalous : Supported Skills have 20% increased Area of Effect',
        alt2: 'Divergent : Supported Skills have 10% increased Skill Effect Duration',
    },
    { 
        level: 4, 
        name: 'Ancestral Call',
        support: 'Support', 
        default: 'Supported Skills have 10% increased Attack Speed',
        alt1: 'Anomalous : Supported Skills have 10% increased Area of Effect',
        alt2: 'Divergent : Supported Skills have +4 to Melee Strike Range',
    },
    { 
        level: 1, 
        name: 'Arcane Surge',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Spell Damage',
        alt1: 'Anomalous : Arcane Surge grants 0% more Spell Damage, Arcane Surge grants 0% increased Cast Speed, Arcane Surge grants 0.2% of Mana Regenerated per second',
        alt2: 'Divergent : Arcane Surge lasts 2 seconds',
    },
    { 
        level: 31, 
        name: 'Archmage',
        support: 'Support', 
        default: 'Supported Skills have 10% increased Mana Cost',
        alt1: 'Anomalous : Supported Skills have base Mana Cost equal to 0% of Unreserved Maximum Mana, if that value is higher, Supported Skills lose Added Lightning Damage equal to 60% of Mana Cost, if Mana Cost is not higher than the maximum you could spend, Supported Skills gain Added Cold Damage equal to 60% of Mana Cost, if Mana Cost is not higher than the maximum you could spend',
        alt2: 'Divergent : Supported Skills have 20% reduced Mana Cost',
    },
    { 
        level: 8, 
        name: 'Arrow Nova',
        support: 'Support', 
        default: 'Supported Skills have 10% increased Attack Speed',
        alt1: 'Anomalous : Supported Skills have 20% increased Projectile Speed',
        alt2: 'Divergent : Supported Skills have 40% reduced Projectile Speed, Supported Skills deal 20% increased Damage',
    },
    { 
        level: 8, 
        name: 'Ballista Totem',
        support: 'Support', 
        default: '20% increased Totem Placement speed',
        alt1: 'Anomalous : 20% increased Totem Duration',
        alt2: 'Divergent : 20% increased Totem Range',
        alt3: 'Phantasmal: 10% chance for Projectiles Fired by Supported Skills to Return'
    },
    { 
        level: 38, 
        name: 'Barrage',
        support: 'Support', 
        default: 'Supported Skills have 10% increased Attack Speed',
        alt1: 'Anomalous : Projectiles from Supported Skills Pierce 2 additional Targets',
        alt2: 'Divergent : Projectiles Fired by Supported Skills have 100% increased Projectile spread',
    },
    { 
        level: 31, 
        name: 'Blasphemy',
        support: 'Support', 
        default: '10% increased Effect of Supported Curses',
        alt1: 'Anomalous : Supported Skills have 40% increased Area of Effect, 10% reduced Effect of Supported Curses',
        alt2: 'Divergent : Supported Skills have 2% reduced Mana Reserved',
    },
    { 
        level: 8, 
        name: 'Blastchain Mine',
        support: 'Support', 
        default: 'Supported Skills have 10% increased Mine Throwing Speed',
        alt1: 'Anomalous : Supported Skills have 20% reduced Mana Reserved',
        alt2: 'Divergent : Mines from Supported Skills have 20% increased Detonation Speed',
    },
    { 
        level: 8, 
        name: 'Blind',
        support: 'Support', 
        default: 'Supported Skills have 20% increased Blinding duration',
        alt1: 'Anomalous : Supported Skills have 10% chance to Blind enemies on hit',
        alt2: 'Divergent : Supported Skills have 40% increased Critical Strike Chance against Blinded Enemies',
    },
    { 
        level: 18, 
        name: 'Block Chance Reduction',
        support: 'Support', 
        default: 'Supported Skills have 5% reduced Enemy Block Chance',
        alt1: 'Anomalous : Supported Skills have 40% increased Overpowered Effect',
    },
    { 
        level: 31, 
        name: 'Blood Magic',
        support: 'Support', 
        default: 'Supported Skills have 10% reduced Mana Cost',
        alt1: 'Anomalous : Supported Skills have 1% reduced Mana Reserved',
        alt2: 'Divergent : Supported Skills Deal 60% increased Damage when on Low Life',
    },
    { 
        level: 18, 
        name: 'Bloodlust',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Melee Damage against Bleeding Enemies',
        alt1: 'Anomalous : Supported Skills have 10% chance to Crush for 2 seconds on Hit',
        alt2: 'Divergent : Supported Skills have 10% chance to refresh Bleeding Duration on Hit',
    },
    { 
        level: 38, 
        name: 'Bonechill',
        support: 'Support', 
        default: 'Supported Skills have 20% increased Chill Duration on Enemies',
        alt1: 'Anomalous : Supported Skills deal 10% increased Cold Damage',
        alt2: 'Divergent : Supported Skills have 10% increased Effect of Chill on Enemies',
    },
    { 
        level: 38, 
        name: 'Brutality',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Physical Damage',
        alt1: 'Anomalous : Supported Attacks have 10% chance to cause Bleeding',
        alt2: 'Divergent : Supported Skills Overwhelm 5% Physical Damage Reduction',
    },
    { 
        level: 31, 
        name: 'Burning Damage',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Burning Damage',
        alt1: 'Anomalous : Supported Skills have 20% increased Ignite Duration on Enemies',
        alt2: 'Divergent : Supported Skills have 40% increased Effect of non-Damaging Ailments on Enemies',
    },
    { 
        level: 38, 
        name: 'Cast On Critical Strike',
        support: 'Support', 
        default: 'Supported Skills have 20% increased Attack Critical Strike Chance, Supported Skills have 20% increased Spell Critical Strike Chance',
        alt1: 'Anomalous : Supported Skills deal 20% more Attack Damage',
        alt2: 'Divergent : Supported Skills have 10% increased Attack Speed',
    },
    { 
        level: 38, 
        name: 'Cast on Death',
        support: 'Support', 
        default: 'Supported Skills have 60% increased Area of Effect while Dead',
        alt1: 'Anomalous : Supported Skills have +100% to Critical Strike Chance while Dead',
        alt2: 'Divergent : Supported Skills have 60% increased Skill Effect Duration while Dead',
    },
    { 
        level: 38, 
        name: 'Cast on Melee Kill',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Attack Damage, Supported Skills deal 10% increased Spell Damage',
        alt1: 'Anomalous : Supported Skills deal 60% increased Attack Damage',
        alt2: 'Divergent : Supported Skills have 20% increased Cooldown Recovery Rate',
    },
    { 
        level: 38, 
        name: 'Cast when Damage Taken',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Damage',
        alt1: 'Anomalous : Supported Skills have 20% increased Skill Effect Duration',
        alt2: 'Divergent : 20% more Damage required to Trigger',
    },
    { 
        level: 38, 
        name: 'Cast when Stunned',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Damage',
        alt1: 'Anomalous : Supported Skills have 20% increased Skill Effect Duration',
        alt2: 'Divergent : 20% chance to Trigger Supported Spells when you are Stunned, or, Block a Stunning Hit',
    },
    { 
        level: 38, 
        name: 'Cast while Channelling',
        support: 'Support', 
        default: 'Supported Channelling Skills deal 10% increased Damage, Supported Triggered Spells deal 10% increased Damage',
        alt1: 'Anomalous : Supported Skills have 10% increased Attack and Cast Speed',
        alt2: 'Divergent : Supported Skills have 10% increased Effect of non-Damaging Ailments on Enemies',
    },
    { 
        level: 38, 
        name: 'Chain',
        support: 'Support', 
        default: 'Supported Skills have 20% increased Projectile Speed',
        alt1: 'Anomalous : Supported Skills have 20% increased Chaining range',
        alt2: 'Divergent : Projectiles Fired by Supported Skills have 80% chance not to Pierce Enemies',
    },
    { 
        level: 1, 
        name: 'Chance to Bleed',
        support: 'Support', 
        default: 'Supported Attacks deal 10% increased Damage with Bleeding',
        alt1: 'Anomalous : Supported Attacks have 20% increased Bleeding Duration',
        alt2: 'Divergent : Supported Skills have 20% more Added Damage',
    },
    { 
        level: 8, 
        name: 'Chance to Flee',
        support: 'Support', 
        default: 'Supported Skills have 20% chance to Cause Monsters to Flee',
        alt1: 'Anomalous : Supported Skills have 10% reduced Cast Speed',
    },
    { 
        level: 31, 
        name: 'Charged Mines',
        support: 'Support', 
        default: '10% increased Mine Damage',
        alt1: 'Anomalous : 10% chance to gain a Frenzy Charge when a Mine from Supported, Skills is Detonated targeting an Enemy, 10% chance to gain a Power Charge when a Mine from Supported, Skills is Detonated targeting an Enemy',
        alt2: 'Divergent : Supported Skills have 4% increased Projectile Speed per Frenzy Charge when used by a Mine',
    },
    { 
        level: 31, 
        name: 'Charged Traps',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Trap Damage',
        alt1: 'Anomalous : Supported Skills have 10% chance to gain a Power Charge when your Trap is triggered by an Enemy, Supported Skills have 10% chance to gain a Frenzy Charge when your Trap is triggered by an Enemy',
        alt2: 'Divergent : Supported Skills have 10% increased Trap Trigger Radius per Power Charge',
    },
    { 
        level: 18, 
        name: 'Close Combat',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Melee Damage',
        alt1: 'Anomalous : 40% increased Effect of Combat Rush granted by Supported Skills',
        alt2: 'Divergent : 20% increased Damage to Close Range Enemies',
    },
    { 
        level: 38, 
        name: 'Cluster Traps',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Trap Damage',
        alt1: 'Anomalous : Supported Skills have 10% increased Trap Throwing Speed',
        alt2: 'Divergent : Supported Skills have 40% reduced Trap Spread',
    },
    { 
        level: 31, 
        name: 'Cold Penetration',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Cold Damage',
        alt1: 'Anomalous : Supported Skills have 10% chance to Freeze',
        alt2: 'Divergent : Supported Skills have 20% increased Effect of Cold Ailments',
    },
    { 
        level: 18, 
        name: 'Cold to Fire',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Cold Damage, Supported Skills deal 10% increased Fire Damage',
        alt1: 'Anomalous : Supported Skills have 10% of Cold Damage Converted to Fire Damage',
        alt2: 'Divergent : Supported Skills deal 60% increased Damage with Poison',
    },
    { 
        level: 8, 
        name: 'Combustion',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Fire Damage',
        alt1: 'Anomalous : Ignites from Supported Skills deal Damage 5% faster',
        alt2: 'Divergent : Supported Skills deal 20% increased Fire Damage, Ignites from Supported Skills deal Damage 10% slower',
    },
    { 
        level: 18, 
        name: 'Concentrated Effect',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Area Damage',
        alt1: 'Anomalous : Supported Skills have 10% less Area of Effect',
        alt2: 'Divergent : Supported Skills have 10% reduced Enemy Stun Threshold',
    },
    { 
        level: 18, 
        name: 'Controlled Destruction',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Spell Damage',
        alt1: 'Anomalous : Supported Skills have 60% reduced Critical Strike Chance, Supported Skills have 10% chance to Freeze, Shock and Ignite',
        alt2: 'Divergent : Supported Skills have 10% chance for Damage with Hits to be Lucky',
    },
    { 
        level: 18, 
        name: 'Culling Strike',
        support: 'Support', 
        default: 'Supported Skills have 10% increased Attack Speed, Supported Skills have 10% increased Cast Speed',
        alt1: 'Anomalous : Supported Skills deal 60% increased Damage with Hits against Enemies that are on Low Life',
        alt2: 'Divergent : Recover 2% of Life when Supported Skills Cull an Enemy',
    },
    { 
        level: 18, 
        name: 'Damage on Full Life',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Damage',
        alt1: 'Anomalous : Supported Skills Leech 0.5% of Attack Damage Leeched as Life',
        alt2: 'Divergent : Supported Skills deal 40% increased Damage with Hits and Ailments against Enemies that are on Full Life',
    },
    { 
        level: 18, 
        name: 'Deadly Ailments',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Damage over Time',
        alt1: 'Anomalous : Supported Skills have 20% increased Duration of Ailments on Enemies',
        alt2: 'Divergent : Supported Skills deal 60% less Damage with Hits, Supported Skills have +10% to Damage over Time Multiplier',
    },
    { 
        level: 38, 
        name: 'Decay',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Chaos Damage',
        alt1: 'Anomalous : Supported Skills have 10% increased Skill Effect Duration',
        alt2: 'Divergent : Supported Skills have 10% of Physical Damage Converted to Chaos Damage',
    },
    { 
        level: 31, 
        name: 'Efficacy',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Damage over Time',
        alt1: 'Anomalous : Supported Skills have 10% increased Skill Effect Duration',
        alt2: 'Divergent : Supported Skills have 10% reduced Mana Cost',
    },
    { 
        level: 31, 
        name: 'Elemental Army',
        support: 'Support', 
        default: 'Minions from Supported Skills have +2% to all maximum Elemental Resistances',
        alt1: 'Anomalous : Minions have 10% increased Area of Effect',
        alt2: 'Divergent : Minions from Supported Skill Leech 0.4% of Elemental Damage as Life',
    },
    { 
        level: 18, 
        name: 'Elemental Damage with Attacks',
        support: 'Support', 
        default: '10% increased Elemental Damage with Attack Skills',
        alt1: 'Anomalous : Supported Skills have 5% chance to Freeze, Shock and Ignite',
        alt2: 'Divergent : 0.5% of Elemental Damage Leeched as Mana',
    },
    { 
        level: 18, 
        name: 'Elemental Focus',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Elemental Damage',
        alt1: 'Anomalous : Supported Skills have 10% increased Area of Effect',
        alt2: 'Divergent : Supported Skills have a 20% Chance to Avoid Interruption from Stuns While Using this Skill',
    },
    { 
        level: 31, 
        name: 'Elemental Penetration',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Elemental Damage',
        alt1: 'Anomalous : Supported Skills have 10% increased Effect of non-Damaging Ailments on Enemies',
    },
    { 
        level: 1, 
        name: 'Elemental Proliferation',
        support: 'Support', 
        default: '10% increased Duration of Elemental Ailments on Enemies',
        alt1: 'Anomalous : Supported Skills have 20% increased Area of Effect',
        alt2: 'Divergent : Supported Skills deal 20% increased Damage with Hits and Ailments per Freeze, Shock or Ignite on Enemy',
    },
    { 
        level: 1, 
        name: 'Empower',
        support: 'Support', 
        default: 'This Gem gains 100% increased Experience',
        alt1: 'Anomalous : 60% reduced Strength Requirement',
    },
    { 
        level: 1, 
        name: 'Endurance Charge on Melee Stun',
        support: 'Support', 
        default: 'Supported Skills have 20% increased Stun Duration on Enemies',
        alt1: 'Anomalous : Supported Skills deal 2% increased Damage per Endurance Charge',
        alt2: 'Divergent : Supported Skills deal 20% increased Damage if you\'ve lost an Endurance Charge in the past 8 seconds',
    },
    { 
        level: 18, 
        name: 'Energy Leech',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Damage while Leeching Energy Shield',
        alt1: 'Anomalous : Supported Skills deal 10% increased Damage while on Full Energy Shield',
        alt2: 'Divergent : Supported Skills have 40% increased Maximum Recovery per Energy Shield Leech',
    },
    { 
        level: 1, 
        name: 'Enhance',
        support: 'Support', 
        default: 'This Gem gains 100% increased Experience',
        alt1: 'Anomalous : 60% reduced Dexterity Requirement',
    },
    { 
        level: 1, 
        name: 'Enlighten',
        support: 'Support', 
        default: 'This Gem gains 100% increased Experience',
        alt1: 'Anomalous : 60% reduced Intelligence Requirement',
    },
    { 
        level: 18, 
        name: 'Faster Attacks',
        support: 'Support', 
        default: 'Supported Skills have 10% increased Attack Speed',
        alt1: 'Anomalous : Supported Skills have 10% increased Cooldown Recovery Rate',
        alt2: 'Divergent : Bleeding inflicted by Supported Skills deals Damage 10% faster',
    },
    { 
        level: 18, 
        name: 'Faster Casting',
        support: 'Support', 
        default: 'Supported Skills have 10% increased Cast Speed',
        alt1: 'Anomalous : Supported Skills have 10% increased Cooldown Recovery Rate',
        alt2: 'Divergent : Ignites from Supported Skills deal Damage 10% faster',
    },
    { 
        level: 31, 
        name: 'Faster Projectiles',
        support: 'Support', 
        default: 'Supported Skills have 10% increased Attack Speed, Supported Skills have 10% increased Cast Speed',
        alt1: 'Anomalous : Projectiles have 60% chance to Return to you from final Target',
        alt2: 'Divergent : Supported Skills have 10% increased Projectile Speed, Supported Skills deal 10% increased Projectile Damage',
    },
    { 
        level: 31, 
        name: 'Feeding Frenzy',
        support: 'Support', 
        default: 'Feeding Frenzy base Duration is 1 second',
        alt1: 'Anomalous : Minions from Supported Skills recover 1% of Life on Hit',
        alt2: 'Divergent : Supported Skills have 10% increased Minion Movement Speed',
    },
    { 
        level: 31, 
        name: 'Fire Penetration',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Fire Damage',
        alt1: 'Anomalous : Supported Skills deal 60% increased Burning Damage',
        alt2: 'Divergent : Supported Skills Destroy Ignited Corpses on Kill',
    },
    { 
        level: 38, 
        name: 'Fist of War',
        support: 'Support', 
        default: 'Supported Skills have 10% increased Area of Effect',
        alt1: 'Anomalous : Supported Skills have 20% reduced Attack Speed, Supported Skills deal 60% increased Damage',
        alt2: 'Divergent : Ancestrally Boosted Slams have 10% reduced Enemy Stun Threshold',
    },
    { 
        level: 31, 
        name: 'Fork',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Projectile Damage',
        alt1: 'Anomalous : Projectiles from Supported Skills have 20% chance for an additional Projectile when Forking',
        alt2: 'Divergent : Projectiles from Supported Skills Pierce an additional Target',
    },
    { 
        level: 31, 
        name: 'Fortify',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Attack Damage',
        alt1: 'Anomalous : Supported Skills have 4% increased Fortify Effect',
        alt2: 'Divergent : Hits from Supported Skills Overwhelm 5% of Physical Damage Reduction while you have Fortify',
    },
    { 
        level: 31, 
        name: 'Generosity',
        support: 'Support', 
        default: 'Supported Skills have 40% increased Aura Area of Effect',
        alt1: 'Anomalous : Non-Curse Auras from Supported Skills have 5% increased Effect',
        alt2: 'Divergent : Supported Skills have 100% increased Aura Area of Effect, Supported Skills have 10% increased Mana Reserved',
    },
    { 
        level: 38, 
        name: 'Greater Multiple Projectiles',
        support: 'Support', 
        default: 'Supported Skills have 10% increased Attack Speed, Supported Skills have 10% increased Cast Speed',
        alt1: 'Anomalous : Supported Skills have 20% reduced Mana Cost, Supported Skills have 10% increased Projectile Speed',
        alt2: 'Divergent : Projectiles Fired by Supported Skills have 20% increased Projectile spread',
    },
    { 
        level: 38, 
        name: 'Greater Volley',
        support: 'Support', 
        default: 'Supported Skills deal 20% increased Projectile Damage',
        alt1: 'Anomalous : 20% increased distance between Firing Points',
        alt2: 'Divergent : Supported Skills have 20% increased Projectile Speed',
    },
    { 
        level: 38, 
        name: 'Hextouch',
        support: 'Support', 
        default: '10% increased Effect of Supported Curses',
        alt1: 'Anomalous : Supported Skills deal 20% increased Damage with Hits and Ailments per Curse on Enemy',
        alt2: 'Divergent : 10% reduced Effect of Supported Curses, Supported Skills have 40% increased Curse Duration',
    },
    { 
        level: 31, 
        name: 'High-Impact Mine',
        support: 'Support', 
        default: 'Supported Skills have 10% increased Mine Throwing Speed',
        alt1: 'Anomalous : Supported Skills have +5% to Critical Strike Multiplier',
        alt2: 'Divergent : Supported Skills have 10% reduced Enemy Stun Threshold',
    },
    { 
        level: 31, 
        name: 'Hypothermia',
        support: 'Support', 
        default: 'Supported Skills have 30% increased Chill Duration on Enemies',
        alt1: 'Anomalous : Supported Skills have +20% chance to Freeze Enemies which are Chilled',
        alt2: 'Divergent : Enemies Frozen by Supported Skills have -4% to Cold Resistance',
    },
    { 
        level: 31, 
        name: 'Ice Bite',
        support: 'Support', 
        default: 'Supported Skills deal 20% increased Damage with Hits against Frozen Enemies',
        alt1: 'Anomalous : Supported Skills deal 2% increased Damage per Frenzy Charge',
        alt2: 'Divergent : Supported Skills have 20% chance to gain a Frenzy Charge on Killing a Frozen Enemy',
    },
    { 
        level: 38, 
        name: 'Ignite Proliferation',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Fire Damage',
        alt1: 'Anomalous : Supported Skills have 10% increased Area of Effect',
        alt2: 'Divergent : Supported Skills have 10% chance to Ignite',
    },
    { 
        level: 38, 
        name: 'Immolate',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Fire Damage',
        alt1: 'Anomalous : Supported Skills have 10% increased Area of Effect',
        alt2: 'Divergent : Supported Skills have 10% chance to Ignite',
    },
    { 
        level: 31, 
        name: 'Impale',
        support: 'Support', 
        default: 'Supported Attacks have 10% increased Impale Effect',
        alt1: 'Anomalous : Supported Attacks have 10% chance to Impale Enemies on Hit',
        alt2: 'Divergent : Supported Skills have 5% chance to inflict an additional Impale on Enemies they Impale',
    },
    { 
        level: 31, 
        name: 'Impending Doom',
        support: 'Support', 
        default: '10% increased Area of Effect',
        alt1: 'Anomalous : Curse Skills have 40% reduced Skill Effect Duration',
        alt2: 'Divergent : +1 Cooldown Use, 25% less Damage per 5 Doom on Hex',
    },
    { 
        level: 38, 
        name: 'Increased Area of Effect',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Area Damage',
        alt1: 'Anomalous : Supported Skills have 10% increased Attack and Cast Speed',
        alt2: 'Divergent : Supported Skills have 10% increased Area of Effect',
    },
    { 
        level: 18, 
        name: 'Increased Critical Damage',
        support: 'Support', 
        default: 'Supported Skills have +15% to Critical Strike Multiplier',
        alt1: 'Anomalous : Supported Skills have 20% increased Critical Strike Chance',
        alt2: 'Divergent : Supported Skills have +30% to Damage over Time Multiplier for Ailments from Critical Strikes',
    },
    { 
        level: 8, 
        name: 'Increased Critical Strikes',
        support: 'Support', 
        default: 'Supported Skills have 20% increased Critical Strike Chance',
        alt1: 'Anomalous : Supported Skills have +5% to Critical Strike Multiplier',
        alt2: 'Divergent : Supported Skills have 10% chance to gain a Power Charge on Kill',
    },
    { 
        level: 31, 
        name: 'Increased Duration',
        support: 'Support', 
        default: 'Supported Skills have 10% increased Skill Effect Duration',
        alt1: 'Anomalous : Supported Skills have 20% reduced Mana Cost, Supported Skills have 10% reduced Skill Effect Duration',
        alt2: 'Divergent : Supported Skills have 20% increased Duration of Ailments on Enemies',
    },
    { 
        level: 8, 
        name: 'Infernal Legion',
        support: 'Support', 
        default: 'Minions from Supported Skills take 20% reduced Fire Damage',
        alt1: 'Anomalous : Minions from Supported Skills take 10% of their Maximum Life as Fire Damage per second',
        alt2: 'Divergent : Minions from Supported Skills deal 30% increased Burning Damage',
    },
    { 
        level: 4, 
        name: 'Infused Channelling',
        support: 'Support', 
        default: 'Gain Infusion after Channelling a Supported Skill for -0.4 seconds',
        alt1: 'Anomalous : 10% increased Effect of Infusion',
        alt2: 'Divergent : Infusion grants 0.5% of Life Regenerated per second',
    },
    { 
        level: 31, 
        name: 'Innervate',
        support: 'Support', 
        default: 'Supported Skills have 30% increased Shock Duration on Enemies',
        alt1: 'Anomalous : Innervation lasts 2 seconds',
        alt2: 'Divergent : 4% chance to gain Innervation when you Shock a Unique Enemy with Supported Skills',
    },
    { 
        level: 31, 
        name: 'Inspiration',
        support: 'Support', 
        default: 'Supported Skills have 20% increased Inspiration Charge Duration',
        alt1: 'Anomalous : Supported Skills have 20% increased Critical Strike Chance',
        alt2: 'Divergent : Supported Skills have 10% reduced Mana Cost',
    },
    { 
        level: 31, 
        name: 'Intensify',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Area Damage',
        alt1: 'Anomalous : Supported Skills have 10% increased Area of Effect',
        alt2: 'Divergent : Lose Intensity 40% faster while moving',
        alt3: 'Phantasmal: Lose Intensity 20% slower while moving',
    },
    { 
        level: 18, 
        name: 'Iron Grip',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Projectile Damage',
        alt1: 'Anomalous : Supported Skills have 10% reduced Attack Speed, Supported Skills deal 40% increased Damage',
        alt2: 'Divergent : Supported Skills have 10% increased Projectile Speed',
    },
    { 
        level: 18, 
        name: 'Iron Will',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Spell Damage',
        alt1: 'Anomalous : Supported Skills have 10% reduced Cast Speed, Supported Skills deal 40% increased Damage',
        alt2: 'Divergent : Supported Skills have 10% increased Projectile Speed',
    },
    { 
        level: 31, 
        name: 'Item Rarity',
        support: 'Support', 
        default: '10% increased Rarity of Items Dropped by Enemies Slain from Supported Skills',
        alt1: 'Anomalous : Supported Skills have 2% chance for Coin Shower on Kill',
    },
    { 
        level: 8, 
        name: 'Knockback',
        support: 'Support', 
        default: 'Supported Skills have 10% chance to Knock Enemies Back on hit',
        alt1: 'Anomalous : Supported Skills deal 10% increased Damage',
        alt2: 'Divergent : Supported Skills have 40% increased Knockback Distance',
    },
    { 
        level: 31, 
        name: 'Less Duration',
        support: 'Support', 
        default: 'Supported Skills have 10% less Skill Effect Duration',
        alt1: 'Anomalous : Supported Skills have 10% increased Attack and Cast Speed',
        alt2: 'Divergent : Bleeding inflicted by Supported Skills deals Damage 10% faster',
    },
    { 
        level: 8, 
        name: 'Lesser Multiple Projectiles',
        support: 'Support', 
        default: 'Supported Skills have 10% increased Attack Speed, Supported Skills have 10% increased Cast Speed',
        alt1: 'Anomalous : Supported Skills have 20% reduced Mana Cost, Supported Skills have 10% increased Projectile Speed',
        alt2: 'Divergent : Projectiles Fired by Supported Skills have 20% increased Projectile spread',
    },
    { 
        level: 1, 
        name: 'Lesser Poison',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Damage with Poison',
        alt1: 'Anomalous : Supported Skills have 4% chance to gain a Frenzy Charge on Killing an Enemy affected by at least 5 Poisons',
        alt2: 'Divergent : Supported Skills deal 20% increased Damage with Hits',
    },
    { 
        level: 8, 
        name: 'Life Gain on Hit',
        support: 'Support', 
        default: '+10 Life gained for each Enemy hit by Attacks from Supported Skills',
        alt1: 'Anomalous : Supported Skills deal 40% increased Damage when on Full Life',
        alt2: 'Divergent : +2 Mana gained for each Enemy hit by Attacks from Supported Skills',
    },
    { 
        level: 31, 
        name: 'Life Leech',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Damage while Leeching Life',
        alt1: 'Anomalous : Supported Skills deal 40% increased Damage when on Full Life',
        alt2: 'Divergent : Supported Skills have 100% increased Maximum Recovery per Life Leech',
    },
    { 
        level: 31, 
        name: 'Lightning Penetration',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Lightning Damage',
        alt1: 'Anomalous : Supported Skills have 10% chance to Shock',
        alt2: 'Divergent : Supported Skills have 20% increased Effect of Lightning Ailments',
    },
    { 
        level: 8, 
        name: 'Maim',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Physical Damage',
        alt1: 'Anomalous : Supported Skill have 20% increased Effect of Maim',
        alt2: 'Divergent : Supported Skills have 10% chance to inflict Bleeding on Maimed Enemies',
    },
    { 
        level: 31, 
        name: 'Mana Leech',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Damage while Leeching Mana',
        alt1: 'Anomalous : Supported Skills have 10% increased Damage for each 200 Mana you have Spent Recently',
        alt2: 'Divergent : +4 Mana gained for each Enemy hit by Attacks from Supported Skills',
    },
    { 
        level: 31, 
        name: 'Meat Shield',
        support: 'Support', 
        default: 'Minions from Supported Skills have 5% additional Physical Damage Reduction',
        alt1: 'Anomalous : Minions from Supported Skills deal 5% more Damage to Enemies that are Near you',
        alt2: 'Divergent : Minions from Supported Skills have +8% Chance to Block Attack Damage',
    },
    { 
        level: 18, 
        name: 'Melee Physical Damage',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Melee Physical Damage',
        alt1: 'Anomalous : Supported Skills have +2 to Melee Strike Range',
        alt2: 'Divergent : Supported Skills Overwhelm 5% Physical Damage Reduction',
    },
    { 
        level: 8, 
        name: 'Melee Splash',
        support: 'Support', 
        default: 'Supported Skills have 10% increased Area of Effect',
        alt1: 'Anomalous : Supported Skills deal 20% increased Melee Damage',
        alt2: 'Divergent : Supported Skills deal 40% more Damage to surrounding targets',
    },
    { 
        level: 38, 
        name: 'Minefield',
        support: 'Support', 
        default: 'Supported Skills have 10% increased Mine Throwing Speed',
        alt1: 'Anomalous : Supported Skills have 4% chance to throw up to 1 additional Mine',
        alt2: 'Divergent : Supported Skills can have up to 4 additional Remote Mines placed at a time',
    },
    { 
        level: 8, 
        name: 'Minion Damage',
        support: 'Support', 
        default: 'Minions from Supported Skills deal 10% increased Damage',
        alt1: 'Anomalous : Minions from Supported Skills have 3% chance to deal Double Damage',
        alt2: 'Divergent : Minions from Supported Skills deal 40% increased Damage with Ailments',
    },
    { 
        level: 18, 
        name: 'Minion Life',
        support: 'Support', 
        default: 'Supported Skills have 15% increased Minion maximum Life',
        alt1: 'Anomalous : Minions Regenerate 1% of Life per second',
        alt2: 'Divergent : Minions from Supported Skills deal 20% increased Damage while on Full Life',
    },
    { 
        level: 18, 
        name: 'Minion Speed',
        support: 'Support', 
        default: 'Supported Skills have 10% increased Minion Movement Speed',
        alt1: 'Anomalous : 40% reduced Minion Duration',
        alt2: 'Divergent : Minions from Supported Skills have 20% increased Cooldown Recovery Rate',
    },
    { 
        level: 4, 
        name: 'Mirage Archer',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Attack Damage',
        alt1: 'Anomalous : Mirage Archer lasts -2 seconds, Mirage Archer fires 2 additional Projectiles with Supported Skills',
        alt2: 'Divergent : Supported Skills have 20% increased Skill Effect Duration',
    },
    { 
        level: 38, 
        name: 'Multiple Totems',
        support: 'Support', 
        default: '20% increased Totem Placement speed',
        alt1: 'Anomalous : 20% increased Totem Duration',
        alt2: 'Divergent : 10% increased Totem Damage',
    },
    { 
        level: 8, 
        name: 'Multiple Traps',
        support: 'Support', 
        default: 'Supported Skills have 20% increased Trap Trigger Area of Effect',
        alt1: 'Anomalous : Supported Skills can have up to 2 additional Traps placed at a time',
        alt2: 'Divergent : Supported Skills have 4% chance to throw an additional Trap',
    },
    { 
        level: 38, 
        name: 'Multistrike',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Melee Physical Damage',
        alt1: 'Anomalous : Supported Skills have 20% reduced Attack Speed, Supported Skills have 20% increased Area of Effect per Repeat',
        alt2: 'Divergent : Supported Skills have 10% increased Attack Speed',
    },
    { 
        level: 18, 
        name: 'Nightblade',
        support: 'Support', 
        default: 'Supported Skills have 20% increased Critical Strike Chance',
        alt1: 'Anomalous : 20% increased Effect of Elusive from Supported Skills',
        alt2: 'Divergent : 100% increased Critical Strike Chance against Enemies on Full Life',
    },
    { 
        level: 1, 
        name: 'Onslaught',
        support: 'Support', 
        default: 'Supported Skills have 10% increased Attack and Cast Speed',
        alt1: 'Anomalous : 20% increased Onslaught duration',
        alt2: 'Divergent : Supported Skills have 20% increased Attack and Cast Speed during Onslaught',
    },
    { 
        level: 18, 
        name: 'Physical to Lightning',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Lightning Damage, Supported Skills deal 10% increased Physical Damage',
        alt1: 'Anomalous : Supported Skills have 10% of Physical Damage Converted to Lightning Damage',
        alt2: 'Divergent : Enemies Shocked by Supported Skills take 10% increased Physical Damage',
    },
    { 
        level: 1, 
        name: 'Pierce',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Projectile Damage',
        alt1: 'Anomalous : Projectiles from Supported Skills Pierce 2 additional Targets',
        alt2: 'Divergent : Projectiles from Supported Skills that have Pierced deal 40% increased Damage',
    },
    { 
        level: 31, 
        name: 'Pinpoint',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Projectile Damage',
        alt1: 'Anomalous : Lose Intensity 20% slower while moving',
        alt2: 'Divergent : Lose Intensity 20% faster while moving',
    },
    { 
        level: 18, 
        name: 'Point Blank',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Projectile Damage',
        alt1: 'Anomalous : Supported Skills have 40% chance to Knock Enemies Back with Hits at Close Range',
        alt2: 'Divergent : Projectiles from Supported Skills Pierce all Targets within 20 units',
    },
    { 
        level: 31, 
        name: 'Poison',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Damage with Poison',
        alt1: 'Anomalous : Supported Skills have 20% chance to Poison on Hit',
        alt2: 'Divergent : Poisons from Supported Skills deal Damage 10% faster',
    },
    { 
        level: 18, 
        name: 'Power Charge On Critical',
        support: 'Support', 
        default: 'Supported Skills have 20% increased Critical Strike Chance',
        alt1: 'Anomalous : Supported Skills have 20% chance to gain a Power Charge on Critical Strike',
        alt2: 'Divergent : Supported Skills deal 2% increased Damage per Power Charge',
    },
    { 
        level: 18, 
        name: 'Predator',
        support: 'Support', 
        default: 'Minions from Supported Skills deal 10% increased Damage',
        alt1: 'Anomalous : Debuff applies -4% to all Resistances',
        alt2: 'Divergent : Minions from Supported Skills have 30% increased Critical Strike Chance against the Prey, Minions from Supported Skills have +15% to Critical Strike Multiplier against the Prey',
    },
    { 
        level: 31, 
        name: 'Pulverise',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Area Damage',
        alt1: 'Anomalous : Supported Skills have 10% increased Area of Effect',
        alt2: 'Divergent : Supported Skills have 10% less Attack Speed, Supported Skills deal 20% more Melee Area Damage',
    },
    { 
        level: 18, 
        name: 'Rage',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Attack Damage',
        alt1: 'Anomalous : Supported Skills have 10% increased Attack Speed while you have at least 20 Rage',
        alt2: 'Divergent : 20% chance to gain 1 Rage when you use Supported Skills',
    },
    { 
        level: 1, 
        name: 'Ruthless',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Attack Damage',
        alt1: 'Anomalous : Supported Skills have 10% increased Attack Speed',
        alt2: 'Divergent : Ruthless Blows with Supported Skills deal 20% more Melee Damage, Supported Skills have 20% reduced Attack Speed',
    },
    { 
        level: 31, 
        name: 'Second Wind',
        support: 'Support', 
        default: 'Supported Skills have 5% increased Cooldown Recovery Rate',
        alt1: 'Anomalous : Supported Skills have 10% reduced Cooldown Recovery Rate, Supported Non-Instant Skills have +1 Cooldown Use',
        alt2: 'Divergent : Regenerate 1% of Life over 1 second when you use Supported Skills',
    },
    { 
        level: 18, 
        name: 'Shockwave',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Melee Damage, 10% increased Melee Damage',
        alt1: 'Anomalous : Supported Skills have 10% increased Area of Effect, 10% increased Area of Effect',
        alt2: 'Divergent : 10% increased Cooldown Recovery Rate',
    },
    { 
        level: 31, 
        name: 'Slower Projectiles',
        support: 'Support', 
        default: 'Supported Skills deal 15% increased Projectile Damage',
        alt1: 'Anomalous : Supported Skills deal 10% increased Projectile Damage to nearby Enemies',
        alt2: 'Divergent : Projectiles Fired by Supported Skills have 60% chance not to Pierce Enemies',
    },
    { 
        level: 4, 
        name: 'Spell Cascade',
        support: 'Support', 
        default: 'Supported Skills have 10% increased Area of Effect',
        alt1: 'Anomalous : Supported Skills deal 10% increased Damage',
        alt2: 'Divergent : Supported Skills have 20% increased Area of Effect, Supported Skills have 100% increased delay between affected Areas',
    },
    { 
        level: 38, 
        name: 'Spell Echo',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Spell Damage',
        alt1: 'Anomalous : Supported Skills have 10% increased Cast Speed',
        alt2: 'Divergent : Supported Skills deal 20% less Damage, Final Repeat of Supported Skills deals 60% more Damage',
    },
    { 
        level: 8, 
        name: 'Spell Totem',
        support: 'Support', 
        default: '20% increased Totem Placement speed',
        alt1: 'Anomalous : 20% increased Totem Duration',
        alt2: 'Divergent : 20% increased Totem Range',
    },
    { 
        level: 8, 
        name: 'Stun',
        support: 'Support', 
        default: 'Supported Skills have 30% increased Stun Duration on Enemies',
        alt1: 'Anomalous : Supported Skills have 4% chance to double Stun Duration',
        alt2: 'Divergent : Recover 1% of Life when you Stun an Enemy with Supported Skills',
    },
    { 
        level: 4, 
        name: 'Summon Phantasm',
        support: 'Support', 
        default: '10% chance to Summon a Phantasm when Supported Skills, or Non-Phantasm Minions, from Supported Skills, deal a Killing Blow',
        alt1: 'Anomalous : 60% increased non-Minion Damage',
        alt2: 'Divergent : Supported Skills have 10% increased Skill Effect Duration',
    },
    { 
        level: 31, 
        name: 'Swift Affliction',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Damage over Time',
        alt1: 'Anomalous : Supported Skills have 5% increased Attack and Cast Speed, Supported Skills have 10% increased Projectile Speed',
        alt2: 'Divergent : You and Enemies have 20% increased Movement Speed while inflicted with an Ailment from Supported Skills',
    },
    { 
        level: 4, 
        name: 'Swift Assembly',
        support: 'Support', 
        default: 'Supported Skills have 10% increased Mine Throwing Speed, Supported Skills have 10% increased Trap Throwing Speed',
        alt1: 'Anomalous : Supported Skills have 40% reduced Trap Duration',
        alt2: 'Divergent : Supported Skills have 2% increased Mine Throwing Speed per Frenzy Charge, Supported Skills have 2% increased Trap Throwing Speed per Frenzy Charge',
    },
    { 
        level: 31, 
        name: 'Swiftbrand',
        support: 'Support', 
        default: 'Supported Skills have 5% increased Activation frequency',
        alt1: 'Anomalous : Supported Skills have 20% more Attached Duration, Supported Skills have 20% less Detached Duration',
        alt2: 'Divergent : Supported Skills have 20% more Activation Frequency if 75% of Attached Duration expired',
    },
    { 
        level: 8, 
        name: 'Trap',
        support: 'Support', 
        default: 'Supported Skills have 10% increased Trap Throwing Speed',
        alt1: 'Anomalous : Supported Skills deal 10% increased Damage',
        alt2: 'Divergent : Supported Skills have 20% increased Trap Trigger Area of Effect',
    },
    { 
        level: 18, 
        name: 'Trap and Mine Damage',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Damage',
        alt1: 'Anomalous : Supported Skills have 10% reduced Mana Cost, Supported Skills have 10% reduced Mana Reserved',
        alt2: 'Divergent : Supported Skills deal 2% increased Damage per Power Charge',
    },
    { 
        level: 8, 
        name: 'Unbound Ailments',
        support: 'Support', 
        default: 'Supported Skills have 10% increased Duration of Ailments on Enemies',
        alt1: 'Anomalous : Supported Skills deal 20% increased Damage with Ailments',
        alt2: 'Divergent : Supported Skills deal 30% increased Damage while you are affected by an Ailment',
    },
    { 
        level: 38, 
        name: 'Unleash',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Spell Damage',
        alt1: 'Anomalous : Supported Skills have 20% increased Cast Speed, Supported Skills have 10% reduced Seal gain frequency',
        alt2: 'Divergent : Supported Skills have 50% increased Seal gain frequency while you are Channelling, Supported Skills have 100% reduced Seal gain frequency while you are not Channelling',
    },
    { 
        level: 31, 
        name: 'Urgent Orders',
        support: 'Support', 
        default: 'Supported Skills have 10% increased Warcry Speed',
        alt1: 'Anomalous : Supported Skills have 20% reduced Cooldown Recovery Rate, Supported Skills have 10% increased Buff Effect',
        alt2: 'Divergent : Supported Skills have minimum of 10 Power',
    },
    { 
        level: 18, 
        name: 'Vicious Projectiles',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Physical Damage',
        alt1: 'Anomalous : Supported Skills have 10% chance to Poison on Hit, Supported Attacks have 10% chance to cause Bleeding',
        alt2: 'Divergent : Supported Attacks have 10% chance to Impale Enemies on Hit',
    },
    { 
        level: 38, 
        name: 'Vile Toxins',
        support: 'Support', 
        default: 'Supported Skills deal 20% increased Damage with Poison',
        alt1: 'Anomalous : Supported Skills have 10% increased Poison Duration',
        alt2: 'Divergent : Poisons from Supported Skills deal Damage 5% faster',
    },
    { 
        level: 8, 
        name: 'Void Manipulation',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Chaos Damage',
        alt1: 'Anomalous : Supported Skills have 5% increased Area of Effect, Supported Skills have 5% increased Attack and Cast Speed',
        alt2: 'Divergent : Supported Skills have 0.4% of Chaos Damage Leeched as Life',
    },
    { 
        level: 4, 
        name: 'Volley',
        support: 'Support', 
        default: 'Supported Skills deal 20% increased Projectile Damage',
        alt1: 'Anomalous : 20% increased distance between Firing Points',
        alt2: 'Divergent : Supported Skills have 10% increased Area of Effect',
    },
    { 
        level: 38, 
        name: 'Withering Touch',
        support: 'Support', 
        default: 'Supported Skills deal 10% increased Chaos Damage',
        alt1: 'Anomalous : Supported Skills have 20% increased Skill Effect Duration',
        alt2: 'Divergent : Supported Skills have a 20% Chance to apply an additional stack of Wither​',
    }
];